// ─────────────────────────────────────────────────────────────────────────────
// COSMIC COMPARE — Data Layer
// All celestial object data used for side-by-side comparison.
// GLB model paths map to files in /public/GLBs/ — fill in as models arrive.
// ─────────────────────────────────────────────────────────────────────────────

export interface CelestialCompareData {
  id: string;
  name: string;
  emoji: string;
  type: string;
  color: string;           // accent hex
  glowColor: string;       // rgba glow
  image: string;           // fallback image for selector

  // Physical
  diameter: string;        // km
  diameterKm: number;      // numeric for bar charts
  radius: string;
  mass: string;
  massKg: number;          // ×10²⁴ kg — use 0 for N/A
  gravity: string;         // m/s²
  gravityMs2: number;
  density: string;         // g/cm³
  surfaceTemp: string;
  surfaceTempC: number;    // °C average/mean
  coreTemp: string;
  atmosphere: string;
  pressure: string;        // atm or bar

  // Orbital
  distanceFromSun: string;
  distanceFromSunAU: number;
  distanceFromEarth: string;
  orbitalSpeed: string;    // km/s
  orbitalSpeedKms: number;
  orbitalPeriod: string;   // Earth years or days
  rotationPeriod: string;

  // Extra
  escapeVelocity: string;  // km/s
  escapeVelocityKms: number;
  magneticField: string;   // relative: none/weak/moderate/strong
  magneticFieldScore: number; // 0–10
  moons: number;
  avgDayLength: string;
  avgYearLength: string;
  age: string;
  composition: string;
  waterPresence: string;
  lifePossibility: string;
  habitability: string;
  terraform: string;
  surfaceType: string;
  color_desc: string;
  discovery: string;
  funFacts: string[];
}

// GLB model paths — replace "" with actual paths once models are added
export const CELESTIAL_MODELS: Record<string, string> = {
  mercury:    "/GLBs/mercury_enhanced_color.glb",
  venus:      "/GLBs/venus.glb",
  earth:      "/GLBs/earth.glb",
  mars:       "/GLBs/mars.glb",
  jupiter:    "/GLBs/jupiter.glb",
  saturn:     "/GLBs/saturn.glb",
  uranus:     "/GLBs/uranus.glb",
  neptune:    "/GLBs/neptune.glb",
  sun:        "/GLBs/sun.glb",
  moon:       "/GLBs/moon.glb",
  pluto:      "",
  iss:        "",
  blackHole:  "/GLBs/black_hole.glb",
  nebula:     "",
  galaxy:     "",
  exoplanet:  "",
  asteroid:   "",
  comet:      "",
};

export const CELESTIAL_OBJECTS: CelestialCompareData[] = [
  {
    id: "mercury", name: "Mercury", emoji: "☿", type: "Terrestrial Planet",
    color: "#b5b5b5", glowColor: "rgba(181,181,181,0.4)", image: "/images/planets/mercury.png",
    diameter: "4,879 km", diameterKm: 4879,
    radius: "2,439 km", mass: "3.30 × 10²³ kg", massKg: 0.330,
    gravity: "3.7 m/s²", gravityMs2: 3.7,
    density: "5.43 g/cm³",
    surfaceTemp: "−180 to 430°C", surfaceTempC: 167,
    coreTemp: "~1,600°C",
    atmosphere: "Extremely thin (sodium, oxygen, hydrogen)",
    pressure: "~10⁻¹⁵ bar",
    distanceFromSun: "57.9 million km", distanceFromSunAU: 0.387,
    distanceFromEarth: "77–222 million km",
    orbitalSpeed: "47.9 km/s", orbitalSpeedKms: 47.9,
    orbitalPeriod: "88 Earth days",
    rotationPeriod: "58.6 Earth days",
    escapeVelocity: "4.25 km/s", escapeVelocityKms: 4.25,
    magneticField: "Very Weak", magneticFieldScore: 1,
    moons: 0, avgDayLength: "176 Earth days", avgYearLength: "88 Earth days",
    age: "4.5 billion years",
    composition: "Iron core, silicate mantle",
    waterPresence: "Ice in polar craters",
    lifePossibility: "Extremely unlikely",
    habitability: "Not habitable",
    terraform: "Theoretically possible but extremely difficult",
    surfaceType: "Rocky, heavily cratered",
    color_desc: "Grey with brown tones",
    discovery: "Known since antiquity; Mariner 10 (1974)",
    funFacts: ["Smallest planet in solar system", "Has no moons", "Day longer than its year", "Has water ice at poles", "Extreme temperature swings"],
  },
  {
    id: "venus", name: "Venus", emoji: "♀", type: "Terrestrial Planet",
    color: "#e8c97a", glowColor: "rgba(232,201,122,0.4)", image: "/images/planets/venus.png",
    diameter: "12,104 km", diameterKm: 12104,
    radius: "6,051 km", mass: "4.87 × 10²⁴ kg", massKg: 4.87,
    gravity: "8.87 m/s²", gravityMs2: 8.87,
    density: "5.24 g/cm³",
    surfaceTemp: "~465°C", surfaceTempC: 465,
    coreTemp: "~5,000°C",
    atmosphere: "Dense CO₂ (96.5%), nitrogen",
    pressure: "92 atm",
    distanceFromSun: "108.2 million km", distanceFromSunAU: 0.723,
    distanceFromEarth: "38–261 million km",
    orbitalSpeed: "35.0 km/s", orbitalSpeedKms: 35.0,
    orbitalPeriod: "225 Earth days",
    rotationPeriod: "243 Earth days (retrograde)",
    escapeVelocity: "10.36 km/s", escapeVelocityKms: 10.36,
    magneticField: "Negligible", magneticFieldScore: 0.5,
    moons: 0, avgDayLength: "117 Earth days", avgYearLength: "225 Earth days",
    age: "4.5 billion years",
    composition: "Iron core, silicate mantle",
    waterPresence: "None (past oceans possible)",
    lifePossibility: "Unlikely (possible in upper atmosphere)",
    habitability: "Not habitable",
    terraform: "Extremely challenging — thick CO₂ atmosphere",
    surfaceType: "Volcanic plains, highlands",
    color_desc: "Yellowish-white cloud tops",
    discovery: "Known since antiquity; Venera probes (1970s)",
    funFacts: ["Hottest planet despite not being closest to Sun", "Rotates backwards", "Day longer than its year", "Crushingly thick atmosphere", "Surface pressure like 900m under ocean"],
  },
  {
    id: "earth", name: "Earth", emoji: "🌍", type: "Terrestrial Planet",
    color: "#4fa3e0", glowColor: "rgba(79,163,224,0.4)", image: "/images/planets/earth.png",
    diameter: "12,756 km", diameterKm: 12756,
    radius: "6,371 km", mass: "5.97 × 10²⁴ kg", massKg: 5.97,
    gravity: "9.81 m/s²", gravityMs2: 9.81,
    density: "5.51 g/cm³",
    surfaceTemp: "−88 to 58°C", surfaceTempC: 15,
    coreTemp: "~5,100°C",
    atmosphere: "Nitrogen (78%), oxygen (21%)",
    pressure: "1 atm",
    distanceFromSun: "149.6 million km", distanceFromSunAU: 1.0,
    distanceFromEarth: "0 km",
    orbitalSpeed: "29.8 km/s", orbitalSpeedKms: 29.8,
    orbitalPeriod: "365.25 days",
    rotationPeriod: "24 hours",
    escapeVelocity: "11.19 km/s", escapeVelocityKms: 11.19,
    magneticField: "Strong", magneticFieldScore: 7,
    moons: 1, avgDayLength: "24 hours", avgYearLength: "365.25 days",
    age: "4.54 billion years",
    composition: "Iron-nickel core, silicate mantle, crust",
    waterPresence: "Abundant (71% surface)",
    lifePossibility: "Confirmed",
    habitability: "Fully habitable",
    terraform: "N/A — already habitable",
    surfaceType: "Oceans, continents, ice caps",
    color_desc: "Blue and green with white clouds",
    discovery: "N/A — home planet",
    funFacts: ["Only known planet with life", "Largest terrestrial planet", "Protected by magnetic field", "71% surface covered by water", "Perfect distance from Sun — Goldilocks zone"],
  },
  {
    id: "mars", name: "Mars", emoji: "♂", type: "Terrestrial Planet",
    color: "#c1440e", glowColor: "rgba(193,68,14,0.4)", image: "/images/planets/mars.png",
    diameter: "6,792 km", diameterKm: 6792,
    radius: "3,390 km", mass: "6.39 × 10²³ kg", massKg: 0.639,
    gravity: "3.72 m/s²", gravityMs2: 3.72,
    density: "3.93 g/cm³",
    surfaceTemp: "−140 to 20°C", surfaceTempC: -63,
    coreTemp: "~1,500°C",
    atmosphere: "Thin CO₂ (95%), nitrogen, argon",
    pressure: "0.006 atm",
    distanceFromSun: "227.9 million km", distanceFromSunAU: 1.524,
    distanceFromEarth: "54.6–401 million km",
    orbitalSpeed: "24.1 km/s", orbitalSpeedKms: 24.1,
    orbitalPeriod: "687 Earth days",
    rotationPeriod: "24h 37m",
    escapeVelocity: "5.03 km/s", escapeVelocityKms: 5.03,
    magneticField: "Very Weak", magneticFieldScore: 0.5,
    moons: 2, avgDayLength: "24h 37m", avgYearLength: "687 Earth days",
    age: "4.5 billion years",
    composition: "Iron oxide (rust), basalt",
    waterPresence: "Ice caps, subsurface brine",
    lifePossibility: "Possible (microbial, past or subsurface)",
    habitability: "Not currently habitable",
    terraform: "Most feasible target in solar system",
    surfaceType: "Rocky desert, volcanoes, canyons",
    color_desc: "Red-orange iron oxide",
    discovery: "Known since antiquity; Mars missions since 1965",
    funFacts: ["Home of Olympus Mons (largest volcano)", "Valles Marineris — canyon system longer than USA", "Two tiny moons: Phobos & Deimos", "Dust storms can cover entire planet", "Most Earth-like planet in solar system"],
  },
  {
    id: "jupiter", name: "Jupiter", emoji: "♃", type: "Gas Giant",
    color: "#c88b3a", glowColor: "rgba(200,139,58,0.4)", image: "/images/planets/jupiter.png",
    diameter: "142,984 km", diameterKm: 142984,
    radius: "71,492 km", mass: "1.90 × 10²⁷ kg", massKg: 1898.0,
    gravity: "24.79 m/s²", gravityMs2: 24.79,
    density: "1.33 g/cm³",
    surfaceTemp: "−110°C (cloud tops)", surfaceTempC: -110,
    coreTemp: "~24,000°C",
    atmosphere: "Hydrogen (90%), helium (10%)",
    pressure: ">1,000 atm",
    distanceFromSun: "778.5 million km", distanceFromSunAU: 5.203,
    distanceFromEarth: "588–968 million km",
    orbitalSpeed: "13.1 km/s", orbitalSpeedKms: 13.1,
    orbitalPeriod: "11.86 Earth years",
    rotationPeriod: "9h 56m",
    escapeVelocity: "59.5 km/s", escapeVelocityKms: 59.5,
    magneticField: "Extremely Strong", magneticFieldScore: 10,
    moons: 95, avgDayLength: "9h 56m", avgYearLength: "11.86 Earth years",
    age: "4.5 billion years",
    composition: "Hydrogen, helium, trace metals",
    waterPresence: "Water vapour in atmosphere",
    lifePossibility: "Unlikely (possible in upper atmosphere)",
    habitability: "Not habitable",
    terraform: "Not feasible — no solid surface",
    surfaceType: "No solid surface — gas bands",
    color_desc: "Orange, brown, white bands",
    discovery: "Known since antiquity; Galileo Galilei (1610) moons",
    funFacts: ["Largest planet in solar system", "Great Red Spot — 400-year storm", "Fastest rotation (less than 10 hours)", "More than twice mass of all other planets combined", "Protects inner planets from asteroids"],
  },
  {
    id: "saturn", name: "Saturn", emoji: "♄", type: "Gas Giant",
    color: "#e4d191", glowColor: "rgba(228,209,145,0.4)", image: "/images/planets/saturn.png",
    diameter: "120,536 km", diameterKm: 120536,
    radius: "60,268 km", mass: "5.68 × 10²⁶ kg", massKg: 568.0,
    gravity: "10.44 m/s²", gravityMs2: 10.44,
    density: "0.69 g/cm³",
    surfaceTemp: "−140°C (cloud tops)", surfaceTempC: -140,
    coreTemp: "~11,700°C",
    atmosphere: "Hydrogen (96%), helium (3%)",
    pressure: ">1,000 atm",
    distanceFromSun: "1.43 billion km", distanceFromSunAU: 9.537,
    distanceFromEarth: "1.2–1.7 billion km",
    orbitalSpeed: "9.7 km/s", orbitalSpeedKms: 9.7,
    orbitalPeriod: "29.5 Earth years",
    rotationPeriod: "10h 42m",
    escapeVelocity: "35.5 km/s", escapeVelocityKms: 35.5,
    magneticField: "Strong", magneticFieldScore: 8,
    moons: 146, avgDayLength: "10h 42m", avgYearLength: "29.5 Earth years",
    age: "4.5 billion years",
    composition: "Hydrogen, helium",
    waterPresence: "Water ice in rings",
    lifePossibility: "Very unlikely",
    habitability: "Not habitable",
    terraform: "Not feasible — no solid surface",
    surfaceType: "No solid surface — gas layers",
    color_desc: "Pale gold with cream bands",
    discovery: "Known since antiquity; rings discovered 1610 Galileo",
    funFacts: ["Less dense than water — would float!", "Most moons of any planet (146)", "Rings made of ice and rock", "Hexagonal storm at north pole", "Titan moon has lakes of liquid methane"],
  },
  {
    id: "uranus", name: "Uranus", emoji: "⛢", type: "Ice Giant",
    color: "#7de8e8", glowColor: "rgba(125,232,232,0.4)", image: "/images/planets/uranus.png",
    diameter: "51,118 km", diameterKm: 51118,
    radius: "25,362 km", mass: "8.68 × 10²⁵ kg", massKg: 86.8,
    gravity: "8.87 m/s²", gravityMs2: 8.87,
    density: "1.27 g/cm³",
    surfaceTemp: "−195°C (cloud tops)", surfaceTempC: -195,
    coreTemp: "~4,700°C",
    atmosphere: "Hydrogen (83%), helium (15%), methane (2.3%)",
    pressure: ">100 atm",
    distanceFromSun: "2.87 billion km", distanceFromSunAU: 19.191,
    distanceFromEarth: "2.6–3.2 billion km",
    orbitalSpeed: "6.8 km/s", orbitalSpeedKms: 6.8,
    orbitalPeriod: "84 Earth years",
    rotationPeriod: "17h 14m (retrograde)",
    escapeVelocity: "21.3 km/s", escapeVelocityKms: 21.3,
    magneticField: "Moderate", magneticFieldScore: 5,
    moons: 27, avgDayLength: "17h 14m", avgYearLength: "84 Earth years",
    age: "4.5 billion years",
    composition: "Water, methane, ammonia ices, hydrogen",
    waterPresence: "Water ice deep in atmosphere",
    lifePossibility: "Very unlikely",
    habitability: "Not habitable",
    terraform: "Not feasible",
    surfaceType: "No solid surface — icy mantle",
    color_desc: "Pale cyan-blue (methane absorption)",
    discovery: "William Herschel, 1781",
    funFacts: ["Rotates on its side (98° tilt)", "Coldest planetary atmosphere", "Has faint rings", "Only planet discovered with a telescope", "Seasons last 21 years each"],
  },
  {
    id: "neptune", name: "Neptune", emoji: "♆", type: "Ice Giant",
    color: "#5b7fde", glowColor: "rgba(91,127,222,0.4)", image: "/images/planets/neptune.png",
    diameter: "49,528 km", diameterKm: 49528,
    radius: "24,622 km", mass: "1.02 × 10²⁶ kg", massKg: 102.0,
    gravity: "11.15 m/s²", gravityMs2: 11.15,
    density: "1.64 g/cm³",
    surfaceTemp: "−200°C (cloud tops)", surfaceTempC: -200,
    coreTemp: "~5,400°C",
    atmosphere: "Hydrogen (80%), helium (19%), methane",
    pressure: ">100 atm",
    distanceFromSun: "4.50 billion km", distanceFromSunAU: 30.07,
    distanceFromEarth: "4.3–4.7 billion km",
    orbitalSpeed: "5.4 km/s", orbitalSpeedKms: 5.4,
    orbitalPeriod: "165 Earth years",
    rotationPeriod: "16h 6m",
    escapeVelocity: "23.5 km/s", escapeVelocityKms: 23.5,
    magneticField: "Strong", magneticFieldScore: 7,
    moons: 16, avgDayLength: "16h 6m", avgYearLength: "165 Earth years",
    age: "4.5 billion years",
    composition: "Water, ammonia, methane ices, hydrogen",
    waterPresence: "Water ice in mantle",
    lifePossibility: "Extremely unlikely",
    habitability: "Not habitable",
    terraform: "Not feasible",
    surfaceType: "No solid surface — icy mantle",
    color_desc: "Deep blue (methane atmosphere)",
    discovery: "Le Verrier & Adams (prediction), Galle 1846",
    funFacts: ["Fastest winds in solar system (2,100 km/h)", "Completed first orbit since discovery in 2011", "Great Dark Spot storm (now gone)", "Triton moon orbits backwards", "Farthest known planet from Sun"],
  },
  {
    id: "sun", name: "Sun", emoji: "☀️", type: "G-type Main Sequence Star",
    color: "#ffa500", glowColor: "rgba(255,165,0,0.5)", image: "/images/planets/sun.png",
    diameter: "1,392,700 km", diameterKm: 1392700,
    radius: "696,340 km", mass: "1.99 × 10³⁰ kg", massKg: 1989000.0,
    gravity: "274 m/s²", gravityMs2: 274,
    density: "1.41 g/cm³",
    surfaceTemp: "~5,500°C", surfaceTempC: 5500,
    coreTemp: "~15,000,000°C",
    atmosphere: "Corona — plasma at millions of °C",
    pressure: "~25 × 10⁹ atm (core)",
    distanceFromSun: "0 km", distanceFromSunAU: 0,
    distanceFromEarth: "149.6 million km",
    orbitalSpeed: "220 km/s (galactic orbit)", orbitalSpeedKms: 220,
    orbitalPeriod: "225 million years (galactic)",
    rotationPeriod: "25–35 days (differential)",
    escapeVelocity: "617.5 km/s", escapeVelocityKms: 617.5,
    magneticField: "Extremely Strong", magneticFieldScore: 10,
    moons: 0, avgDayLength: "~25 Earth days", avgYearLength: "225 million years (galactic)",
    age: "4.6 billion years",
    composition: "Hydrogen (73%), helium (25%), trace metals",
    waterPresence: "None",
    lifePossibility: "No",
    habitability: "Not habitable",
    terraform: "Not possible",
    surfaceType: "Plasma (photosphere)",
    color_desc: "White (appears yellow from Earth)",
    discovery: "N/A — central star of solar system",
    funFacts: ["Contains 99.86% of solar system's mass", "Sunlight takes 8 minutes to reach Earth", "About halfway through its life", "Core fuses 600 million tons H per second", "Solar flares can affect Earth's technology"],
  },
  {
    id: "moon", name: "Moon", emoji: "🌕", type: "Natural Satellite",
    color: "#c8c8c8", glowColor: "rgba(200,200,200,0.4)", image: "/images/planets/moon.png",
    diameter: "3,474 km", diameterKm: 3474,
    radius: "1,737 km", mass: "7.34 × 10²² kg", massKg: 0.0734,
    gravity: "1.62 m/s²", gravityMs2: 1.62,
    density: "3.35 g/cm³",
    surfaceTemp: "−173 to 127°C", surfaceTempC: -20,
    coreTemp: "~1,400°C",
    atmosphere: "Extremely thin exosphere",
    pressure: "~3 × 10⁻¹⁵ atm",
    distanceFromSun: "149.6 million km", distanceFromSunAU: 1.0,
    distanceFromEarth: "384,400 km",
    orbitalSpeed: "1.022 km/s", orbitalSpeedKms: 1.022,
    orbitalPeriod: "27.3 days",
    rotationPeriod: "27.3 days (synchronous)",
    escapeVelocity: "2.38 km/s", escapeVelocityKms: 2.38,
    magneticField: "None", magneticFieldScore: 0,
    moons: 0, avgDayLength: "29.5 Earth days", avgYearLength: "N/A",
    age: "4.5 billion years",
    composition: "Anorthosite crust, iron-nickel core",
    waterPresence: "Ice in permanently shadowed craters",
    lifePossibility: "Unlikely without terraforming",
    habitability: "Not currently habitable",
    terraform: "Feasible with infrastructure",
    surfaceType: "Rocky, cratered, regolith",
    color_desc: "Grey with white highlands",
    discovery: "Known since prehistory; first visited Apollo 11 (1969)",
    funFacts: ["Only other world humans have walked on", "Causes Earth's tides", "Moving away from Earth ~3.8 cm/year", "Same side always faces Earth", "Water ice confirmed at south pole"],
  },
  {
    id: "pluto", name: "Pluto", emoji: "🌑", type: "Dwarf Planet",
    color: "#a0896a", glowColor: "rgba(160,137,106,0.4)", image: "/images/planets/pluto.png",
    diameter: "2,377 km", diameterKm: 2377,
    radius: "1,188 km", mass: "1.31 × 10²² kg", massKg: 0.0131,
    gravity: "0.62 m/s²", gravityMs2: 0.62,
    density: "1.85 g/cm³",
    surfaceTemp: "−218 to −233°C", surfaceTempC: -225,
    coreTemp: "~900°C",
    atmosphere: "Thin nitrogen, methane, CO",
    pressure: "~0.00001 atm",
    distanceFromSun: "5.9 billion km", distanceFromSunAU: 39.48,
    distanceFromEarth: "4.28–7.5 billion km",
    orbitalSpeed: "4.7 km/s", orbitalSpeedKms: 4.7,
    orbitalPeriod: "248 Earth years",
    rotationPeriod: "6.39 Earth days (retrograde)",
    escapeVelocity: "1.21 km/s", escapeVelocityKms: 1.21,
    magneticField: "None detected", magneticFieldScore: 0,
    moons: 5, avgDayLength: "6.39 Earth days", avgYearLength: "248 Earth years",
    age: "4.5 billion years",
    composition: "Rock, water ice, nitrogen ice",
    waterPresence: "Water ice beneath surface",
    lifePossibility: "Very unlikely",
    habitability: "Not habitable",
    terraform: "Extremely difficult",
    surfaceType: "Icy plains, mountains",
    color_desc: "Reddish-brown with white plains",
    discovery: "Clyde Tombaugh, 1930; reclassified 2006",
    funFacts: ["Reclassified as dwarf planet in 2006", "Has a heart-shaped nitrogen plain", "Charon is half Pluto's size — binary system", "New Horizons flyby 2015", "Atmosphere freezes and collapses each orbit"],
  },
  {
    id: "iss", name: "ISS", emoji: "🛰️", type: "Space Station",
    color: "#94c8ff", glowColor: "rgba(148,200,255,0.4)", image: "/images/space-explorer/ISSTracker.png",
    diameter: "109 m (width)", diameterKm: 0.109,
    radius: "~55 m", mass: "~420,000 kg", massKg: 0.00042,
    gravity: "~0 m/s² (microgravity)", gravityMs2: 0,
    density: "N/A",
    surfaceTemp: "−157 to 121°C (exterior)", surfaceTempC: 22,
    coreTemp: "N/A",
    atmosphere: "Earth-like (controlled)",
    pressure: "~1 atm (interior)",
    distanceFromSun: "~149.6 million km", distanceFromSunAU: 1.0,
    distanceFromEarth: "~408 km altitude",
    orbitalSpeed: "7.66 km/s", orbitalSpeedKms: 7.66,
    orbitalPeriod: "~92 minutes",
    rotationPeriod: "N/A",
    escapeVelocity: "N/A", escapeVelocityKms: 0,
    magneticField: "None", magneticFieldScore: 0,
    moons: 0, avgDayLength: "~92 minutes (orbit)", avgYearLength: "N/A",
    age: "Launched 1998",
    composition: "Aluminum, titanium, steel, solar panels",
    waterPresence: "Recycled water onboard",
    lifePossibility: "Artificially maintained",
    habitability: "Habitable (artificial)",
    terraform: "N/A",
    surfaceType: "Metal structure with solar arrays",
    color_desc: "Silver with gold solar panels",
    discovery: "First module Zarya launched Nov 1998",
    funFacts: ["Orbits Earth 15–16 times per day", "Size of a football field", "International crew since 2000", "Visible to naked eye from Earth", "Traveling at ~28,000 km/h"],
  },
  {
    id: "blackHole", name: "Black Hole", emoji: "🕳️", type: "Stellar Remnant",
    color: "#8b5cf6", glowColor: "rgba(139,92,246,0.5)", image: "/images/space-explorer/BlackHole.png",
    diameter: "Varies (Sgr A*: ~44 million km)", diameterKm: 44000000,
    radius: "Schwarzschild radius", mass: "4 million M☉ (Sgr A*)", massKg: 0,
    gravity: "Infinite at singularity", gravityMs2: 999999,
    density: "Infinite at singularity",
    surfaceTemp: "Near absolute zero (Hawking)", surfaceTempC: -273,
    coreTemp: "Singularity — undefined",
    atmosphere: "None — accretion disk of plasma",
    pressure: "Infinite at singularity",
    distanceFromSun: "Sgr A*: 26,000 light-years", distanceFromSunAU: 0,
    distanceFromEarth: "Sgr A*: 26,000 light-years",
    orbitalSpeed: "N/A", orbitalSpeedKms: 0,
    orbitalPeriod: "N/A",
    rotationPeriod: "N/A (Kerr black holes spin)",
    escapeVelocity: "> Speed of light", escapeVelocityKms: 299792,
    magneticField: "Extremely Strong", magneticFieldScore: 10,
    moons: 0, avgDayLength: "N/A", avgYearLength: "N/A",
    age: "Varies — some primordial",
    composition: "Singularity — point mass",
    waterPresence: "None",
    lifePossibility: "No",
    habitability: "Not habitable",
    terraform: "Not possible",
    surfaceType: "Event horizon — no physical surface",
    color_desc: "Black with glowing accretion disk",
    discovery: "Karl Schwarzschild (theoretical 1916); Sgr A* confirmed 2022",
    funFacts: ["Nothing — not even light — can escape", "Time slows near event horizon", "First imaged in 2019 (M87*)", "Milky Way centre hosts Sgr A*", "Spaghettification tears apart matter"],
  },
  {
    id: "nebula", name: "Nebula", emoji: "🌌", type: "Interstellar Cloud",
    color: "#e879f9", glowColor: "rgba(232,121,249,0.4)", image: "/images/space-explorer/Nebulae.png",
    diameter: "Varies (Orion: ~24 light-years)", diameterKm: 0,
    radius: "Varies", mass: "~300 M☉ (Orion)", massKg: 0,
    gravity: "Extremely weak", gravityMs2: 0,
    density: "~10⁻¹⁹ g/cm³ (near vacuum)",
    surfaceTemp: "−260 to 10,000°C", surfaceTempC: -260,
    coreTemp: "N/A",
    atmosphere: "Hydrogen, helium, dust, plasma",
    pressure: "Near vacuum",
    distanceFromSun: "Orion: 1,344 light-years", distanceFromSunAU: 0,
    distanceFromEarth: "Varies (hundreds to thousands of LY)",
    orbitalSpeed: "N/A", orbitalSpeedKms: 0,
    orbitalPeriod: "N/A",
    rotationPeriod: "N/A",
    escapeVelocity: "N/A", escapeVelocityKms: 0,
    magneticField: "Weak magnetic fields", magneticFieldScore: 2,
    moons: 0, avgDayLength: "N/A", avgYearLength: "N/A",
    age: "Millions of years",
    composition: "Hydrogen (90%), helium, dust, trace metals",
    waterPresence: "Water molecules detected",
    lifePossibility: "Unlikely (stellar nursery — pre-stellar)",
    habitability: "Not habitable",
    terraform: "Not possible",
    surfaceType: "No surface — gas and dust cloud",
    color_desc: "Colorful — red (H-alpha), blue (reflection), green",
    discovery: "Messier catalogued many in 1700s; JWST reveals details",
    funFacts: ["Birthplace of stars and planetary systems", "Some span hundreds of light-years", "Pillars of Creation inside Eagle Nebula", "JWST captured unprecedented nebula detail", "Beautiful colors from ionized gases"],
  },
  {
    id: "galaxy", name: "Galaxy", emoji: "🌀", type: "Galaxy (Milky Way)",
    color: "#60a5fa", glowColor: "rgba(96,165,250,0.4)", image: "/images/space-explorer/Galaxies.png",
    diameter: "~105,700 light-years", diameterKm: 0,
    radius: "~52,850 light-years", mass: "~1.5 × 10¹² M☉", massKg: 0,
    gravity: "Varies", gravityMs2: 0,
    density: "Extremely low average",
    surfaceTemp: "N/A", surfaceTempC: -270,
    coreTemp: "Billions °C (black hole)",
    atmosphere: "Interstellar medium",
    pressure: "Near vacuum",
    distanceFromSun: "0 (we are inside)", distanceFromSunAU: 0,
    distanceFromEarth: "0 (we are inside)",
    orbitalSpeed: "220 km/s (Sun around center)", orbitalSpeedKms: 220,
    orbitalPeriod: "225 million years (Sun)",
    rotationPeriod: "N/A — differential rotation",
    escapeVelocity: "N/A", escapeVelocityKms: 0,
    magneticField: "Galactic magnetic field", magneticFieldScore: 3,
    moons: 0, avgDayLength: "N/A", avgYearLength: "N/A",
    age: "~13.6 billion years",
    composition: "Stars, dark matter, gas, dust",
    waterPresence: "Water across solar systems",
    lifePossibility: "Contains billions of potentially habitable planets",
    habitability: "Contains habitable zones",
    terraform: "N/A",
    surfaceType: "No surface — spiral structure",
    color_desc: "White core, blue arms (BVRI composite)",
    discovery: "Structure mapped by William Herschel ~1785",
    funFacts: ["Contains 100–400 billion stars", "Andromeda galaxy will merge in 4.5 billion years", "Has at least one supermassive black hole at center", "Dark matter makes up ~27% of universe", "Part of the Local Group of ~50 galaxies"],
  },
  {
    id: "exoplanet", name: "Exoplanet", emoji: "🪐", type: "Exoplanet (Kepler-452b)",
    color: "#34d399", glowColor: "rgba(52,211,153,0.4)", image: "/images/space-explorer/ExoPlanet.png",
    diameter: "~18,000 km (est.)", diameterKm: 18000,
    radius: "~1.6 × Earth", mass: "~5 × Earth mass", massKg: 29.85,
    gravity: "~17 m/s² (est.)", gravityMs2: 17,
    density: "~5 g/cm³ (est.)",
    surfaceTemp: "~−28°C (est.)", surfaceTempC: -28,
    coreTemp: "Unknown",
    atmosphere: "Unknown — possibly thick",
    pressure: "Unknown",
    distanceFromSun: "1,402 light-years", distanceFromSunAU: 0,
    distanceFromEarth: "1,402 light-years",
    orbitalSpeed: "~29 km/s (est.)", orbitalSpeedKms: 29,
    orbitalPeriod: "385 days",
    rotationPeriod: "Unknown",
    escapeVelocity: "~18 km/s (est.)", escapeVelocityKms: 18,
    magneticField: "Unknown", magneticFieldScore: 5,
    moons: 0, avgDayLength: "Unknown", avgYearLength: "385 days",
    age: "6 billion years",
    composition: "Unknown — likely rock and water",
    waterPresence: "Possible (in habitable zone)",
    lifePossibility: "Possible",
    habitability: "Potentially habitable",
    terraform: "Unknown",
    surfaceType: "Unknown",
    color_desc: "Unknown",
    discovery: "NASA Kepler mission, 2015",
    funFacts: ["'Earth's older cousin'", "In habitable zone of Sun-like star", "One of the most Earth-like exoplanets found", "Kepler Space Telescope discovered it", "Over 5,500 confirmed exoplanets known"],
  },
  {
    id: "asteroid", name: "Asteroid", emoji: "☄", type: "Asteroid (Ceres/Apophis)",
    color: "#9ca3af", glowColor: "rgba(156,163,175,0.4)", image: "/images/space-explorer/Asteroid.png",
    diameter: "0.1m–940 km (Ceres)", diameterKm: 940,
    radius: "~470 km (Ceres)", mass: "9.4 × 10²⁰ kg (Ceres)", massKg: 0.00094,
    gravity: "0.28 m/s² (Ceres)", gravityMs2: 0.28,
    density: "2.2 g/cm³",
    surfaceTemp: "−106°C (avg)", surfaceTempC: -106,
    coreTemp: "Unknown",
    atmosphere: "None",
    pressure: "None",
    distanceFromSun: "2.2–3.2 AU (main belt)", distanceFromSunAU: 2.7,
    distanceFromEarth: "Varies",
    orbitalSpeed: "17.9 km/s (Ceres)", orbitalSpeedKms: 17.9,
    orbitalPeriod: "4.6 years (Ceres)",
    rotationPeriod: "9.07 hours (Ceres)",
    escapeVelocity: "0.51 km/s (Ceres)", escapeVelocityKms: 0.51,
    magneticField: "None", magneticFieldScore: 0,
    moons: 0, avgDayLength: "9 hours (Ceres)", avgYearLength: "4.6 years (Ceres)",
    age: "4.5 billion years",
    composition: "Rock, metal, carbon compounds",
    waterPresence: "Water ice (Ceres)",
    lifePossibility: "Very unlikely",
    habitability: "Not habitable",
    terraform: "Not feasible",
    surfaceType: "Rocky, irregular, cratered",
    color_desc: "Dark grey to black",
    discovery: "Ceres: Piazzi 1801; thousands discovered since",
    funFacts: ["Millions exist in asteroid belt", "DART mission redirected Dimorphos 2022", "Ceres is also a dwarf planet", "Some contain rare metals", "Apophis will pass very close in 2029"],
  },
  {
    id: "comet", name: "Comet", emoji: "☄️", type: "Comet (Halley's)",
    color: "#67e8f9", glowColor: "rgba(103,232,249,0.4)", image: "/images/space-explorer/Comet.png",
    diameter: "15 × 8 km (nucleus)", diameterKm: 15,
    radius: "~7.5 km (nucleus)", mass: "2.2 × 10¹⁴ kg", massKg: 0,
    gravity: "~0.00017 m/s²", gravityMs2: 0.00017,
    density: "0.6 g/cm³",
    surfaceTemp: "−70 to 77°C", surfaceTempC: -70,
    coreTemp: "Unknown",
    atmosphere: "Coma (sublimated gas/dust near Sun)",
    pressure: "None (nucleus)",
    distanceFromSun: "0.6–35 AU (Halley)", distanceFromSunAU: 17.8,
    distanceFromEarth: "Varies",
    orbitalSpeed: "54.6 km/s (perihelion)", orbitalSpeedKms: 54.6,
    orbitalPeriod: "75–76 years (Halley)",
    rotationPeriod: "~52 hours (Halley)",
    escapeVelocity: "~0.001 km/s", escapeVelocityKms: 0.001,
    magneticField: "None", magneticFieldScore: 0,
    moons: 0, avgDayLength: "N/A", avgYearLength: "75–76 years",
    age: "4.5 billion years",
    composition: "Water ice, dust, CO₂, organics",
    waterPresence: "Mostly water ice",
    lifePossibility: "Very unlikely",
    habitability: "Not habitable",
    terraform: "Not feasible",
    surfaceType: "Icy nucleus, dark crust",
    color_desc: "White/blue tail, dark nucleus",
    discovery: "Halley: known since 240 BC; Edmond Halley 1705 (periodicity)",
    funFacts: ["Tail always points away from Sun", "Rosetta mission landed on comet 67P", "Halley's visible every ~75 years", "May have delivered water to early Earth", "Oort Cloud — reservoir of trillions of comets"],
  },
];

export function getCelestialById(id: string): CelestialCompareData | undefined {
  return CELESTIAL_OBJECTS.find((o) => o.id === id);
}
