import { Planet } from "@/types";

export const PLANETS: Planet[] = [
  {
    id: "mercury",
    name: "Mercury",
    radius: 0.38,
    distance: 5,
    orbitalPeriod: 0.24,
    rotationPeriod: 58.6,
    texture: "/textures/mercury.jpg",
    color: "#b5b5b5",
    glowColor: "#c8c8c8",
    tilt: 0.034,
    description: "The smallest planet and closest to the Sun",
    distanceSun: "57.9 million km",
    diameter: "4,879 km",
    gravity: "3.7 m/s²",
    temperature: "-180°C to 430°C",
    atmosphere: "Virtually none (trace sodium, oxygen, hydrogen)",
    funFacts: [
      "A year on Mercury lasts only 88 Earth days",
      "Mercury has the most extreme temperature variation of any planet",
      "Despite being closest to the Sun, Venus is hotter",
      "Mercury's core makes up 85% of its radius",
    ],
    moons: 0,
    type: "terrestrial",
  },
  {
    id: "venus",
    name: "Venus",
    radius: 0.95,
    distance: 8,
    orbitalPeriod: 0.62,
    rotationPeriod: -243,
    texture: "/textures/venus.jpg",
    color: "#e8cda0",
    glowColor: "#f0d060",
    tilt: 177.4,
    description: "Earth's twin in size but a hellish greenhouse world",
    distanceSun: "108.2 million km",
    diameter: "12,104 km",
    gravity: "8.87 m/s²",
    temperature: "462°C (average)",
    atmosphere: "96.5% CO₂, 3.5% Nitrogen",
    funFacts: [
      "Venus rotates backwards compared to most planets",
      "A day on Venus is longer than a year on Venus",
      "Venus is the hottest planet despite Mercury being closer to the Sun",
      "Atmospheric pressure is 92 times that of Earth",
    ],
    moons: 0,
    type: "terrestrial",
  },
  {
    id: "earth",
    name: "Earth",
    radius: 1,
    distance: 12,
    orbitalPeriod: 1,
    rotationPeriod: 1,
    texture: "/textures/earth_daymap.jpg",
    bumpMap: "/textures/earth_normal.jpg",
    specularMap: "/textures/earth_specular.jpg",
    color: "#4a9eff",
    glowColor: "#6bb8ff",
    tilt: 23.4,
    hasMoon: true,
    description: "Our pale blue dot — the only known harbor of life",
    distanceSun: "149.6 million km",
    diameter: "12,742 km",
    gravity: "9.81 m/s²",
    temperature: "-88°C to 58°C",
    atmosphere: "78% Nitrogen, 21% Oxygen, 1% Argon",
    funFacts: [
      "Earth is the densest planet in the solar system",
      "The Moon is slowly drifting away at 3.8 cm per year",
      "Earth's magnetic field protects us from solar wind",
      "70% of Earth's surface is covered in water",
    ],
    moons: 1,
    type: "terrestrial",
  },
  {
    id: "mars",
    name: "Mars",
    radius: 0.53,
    distance: 16,
    orbitalPeriod: 1.88,
    rotationPeriod: 1.03,
    texture: "/textures/mars.jpg",
    color: "#c1440e",
    glowColor: "#e05020",
    tilt: 25.2,
    description: "The Red Planet — humanity's next great frontier",
    distanceSun: "227.9 million km",
    diameter: "6,779 km",
    gravity: "3.72 m/s²",
    temperature: "-125°C to 20°C",
    atmosphere: "95.3% CO₂, 2.7% Nitrogen, 1.6% Argon",
    funFacts: [
      "Mars has the tallest volcano in the solar system — Olympus Mons",
      "A Martian day (sol) is 24 hours 37 minutes",
      "Mars has two moons: Phobos and Deimos",
      "The Valles Marineris canyon is as wide as the United States",
    ],
    moons: 2,
    type: "terrestrial",
  },
  {
    id: "jupiter",
    name: "Jupiter",
    radius: 11.2,
    distance: 28,
    orbitalPeriod: 11.86,
    rotationPeriod: 0.41,
    texture: "/textures/jupiter.jpg",
    color: "#c88b3a",
    glowColor: "#e0a050",
    tilt: 3.1,
    description: "King of the planets — a colossal gas giant",
    distanceSun: "778.5 million km",
    diameter: "139,820 km",
    gravity: "24.79 m/s²",
    temperature: "-108°C (cloud tops)",
    atmosphere: "90% Hydrogen, 10% Helium, trace methane, ammonia",
    funFacts: [
      "Jupiter's Great Red Spot is a storm larger than Earth",
      "Jupiter has at least 95 known moons",
      "One day on Jupiter is only 10 hours long",
      "Jupiter acts as a gravitational shield protecting inner planets",
    ],
    moons: 95,
    type: "gas-giant",
  },
  {
    id: "saturn",
    name: "Saturn",
    radius: 9.45,
    distance: 42,
    orbitalPeriod: 29.46,
    rotationPeriod: 0.45,
    texture: "/textures/saturn.jpg",
    color: "#e4d191",
    glowColor: "#f0e080",
    tilt: 26.7,
    hasRings: true,
    ringColor: "#c8b060",
    description: "The ringed jewel of the solar system",
    distanceSun: "1.43 billion km",
    diameter: "116,460 km",
    gravity: "10.44 m/s²",
    temperature: "-139°C (cloud tops)",
    atmosphere: "96% Hydrogen, 3% Helium",
    funFacts: [
      "Saturn's rings are made of ice and rock, spanning 282,000 km",
      "Saturn is the least dense planet — it could float on water",
      "Saturn has 146 known moons including Titan with a thick atmosphere",
      "Saturn's rings will eventually disappear in 100 million years",
    ],
    moons: 146,
    type: "gas-giant",
  },
  {
    id: "uranus",
    name: "Uranus",
    radius: 4.01,
    distance: 56,
    orbitalPeriod: 84.01,
    rotationPeriod: -0.72,
    texture: "/textures/uranus.jpg",
    color: "#7de8e8",
    glowColor: "#9fffff",
    tilt: 97.8,
    hasRings: true,
    ringColor: "#5090a0",
    description: "The ice giant that rotates on its side",
    distanceSun: "2.87 billion km",
    diameter: "50,724 km",
    gravity: "8.87 m/s²",
    temperature: "-197°C (average)",
    atmosphere: "83% Hydrogen, 15% Helium, 2% Methane",
    funFacts: [
      "Uranus rotates on its side with an axial tilt of 98 degrees",
      "Uranus is the coldest planet with a minimum temperature of -224°C",
      "Uranus has 13 known rings and 28 moons",
      "A year on Uranus equals 84 Earth years",
    ],
    moons: 28,
    type: "ice-giant",
  },
  {
    id: "neptune",
    name: "Neptune",
    radius: 3.88,
    distance: 70,
    orbitalPeriod: 164.8,
    rotationPeriod: 0.67,
    texture: "/textures/neptune.jpg",
    color: "#5b5ddf",
    glowColor: "#7070ff",
    tilt: 28.3,
    description: "The windiest planet at the edge of the solar system",
    distanceSun: "4.5 billion km",
    diameter: "49,244 km",
    gravity: "11.15 m/s²",
    temperature: "-201°C (average)",
    atmosphere: "80% Hydrogen, 19% Helium, 1% Methane",
    funFacts: [
      "Neptune has the strongest winds in the solar system — 2,100 km/h",
      "Neptune was predicted mathematically before it was observed",
      "Neptune's moon Triton orbits backwards",
      "One year on Neptune is 165 Earth years",
    ],
    moons: 16,
    type: "ice-giant",
  },
  {
    id: "pluto",
    name: "Pluto",
    radius: 0.18,
    distance: 82,
    orbitalPeriod: 247.9,
    rotationPeriod: -6.39,
    texture: "/textures/pluto.jpg",
    color: "#c8b89a",
    glowColor: "#d0c0a0",
    tilt: 122.5,
    description: "The beloved dwarf planet at the edge of our solar system",
    distanceSun: "5.9 billion km",
    diameter: "2,377 km",
    gravity: "0.62 m/s²",
    temperature: "-233°C (average)",
    atmosphere: "Thin nitrogen, methane, carbon monoxide",
    funFacts: [
      "Pluto was reclassified as a dwarf planet in 2006",
      "Pluto's heart-shaped nitrogen ice plain is called Tombaugh Regio",
      "Pluto has 5 moons — its largest, Charon, is half Pluto's size",
      "New Horizons flew past Pluto in 2015 sending stunning images",
    ],
    moons: 5,
    type: "dwarf",
  },
];

export const SUN_DATA = {
  name: "The Sun",
  radius: 5,
  color: "#FDB813",
  glowColor: "#FF6600",
  temperature: "5,500°C (surface) / 15 million°C (core)",
  diameter: "1,392,700 km",
  description: "Our star — a G-type main-sequence star at the center of the solar system",
  funFacts: [
    "The Sun contains 99.86% of the solar system's total mass",
    "Light from the Sun takes 8 minutes to reach Earth",
    "The Sun is 4.6 billion years old and halfway through its life",
    "The Sun's surface temperature is about 5,500°C",
  ],
};
