export interface SpaceCategory {
  slug: string;
  icon: string;
  title: string;
  subtitle: string;
  description: string;
  accent: string;
  glow: string;
  status: string;
  statusColor: string;
  image: string;
  tags: string[];
}

export interface SpaceDetailData {
  slug: string;
  title: string;
  subtitle: string;
  icon: string;
  heroImage: string;
  accent: string;
  overview: string;
  stats: { label: string; value: string; unit?: string }[];
  facts: string[];
  timeline: { year: string; event: string; detail: string }[];
  missions: { name: string; agency: string; status: string; year: string; description: string }[];
  gallery: { src: string; caption: string }[];
  relatedSlugs: string[];
  aiPrompts: string[];
  apiSource?: string;
}

export const SPACE_CATEGORIES: SpaceCategory[] = [
  {
    slug: "solar-system",
    icon: "🪐",
    title: "Solar System",
    subtitle: "Our Cosmic Home",
    description: "Eight planets, hundreds of moons, millions of asteroids orbiting our star.",
    accent: "#f59e0b",
    glow: "rgba(245,158,11,0.35)",
    status: "8 Planets",
    statusColor: "#f59e0b",
    image: "/images/space-explorer/SolarSystemSpaceExplorer.png",
    tags: ["Planets", "Moons", "Orbits"],
  },
  {
    slug: "dwarf-planets",
    icon: "🌠",
    title: "Dwarf Planets",
    subtitle: "Beyond Neptune",
    description: "Pluto, Eris, Makemake and the fascinating worlds of the outer solar system.",
    accent: "#a78bfa",
    glow: "rgba(167,139,250,0.35)",
    status: "5 Classified",
    statusColor: "#a78bfa",
    image: "/images/space-explorer/DwarfPlanets.png",
    tags: ["Pluto", "Kuiper Belt", "Trans-Neptunian"],
  },
  {
    slug: "asteroids",
    icon: "☄",
    title: "Asteroids",
    subtitle: "Rocky Remnants",
    description: "Rocky leftovers from solar system formation, spanning from dust to hundreds of km wide.",
    accent: "#94a3b8",
    glow: "rgba(148,163,184,0.35)",
    status: "1M+ Known",
    statusColor: "#94a3b8",
    image: "/images/space-explorer/Asteroid.png",
    tags: ["NEO", "Asteroid Belt", "Impact"],
  },
  {
    slug: "comets",
    icon: "☄",
    title: "Comets",
    subtitle: "Icy Wanderers",
    description: "Icy bodies from the outer solar system that display glowing tails as they approach the Sun.",
    accent: "#67e8f9",
    glow: "rgba(103,232,249,0.35)",
    status: "Active Tracking",
    statusColor: "#67e8f9",
    image: "/images/space-explorer/Comet.png",
    tags: ["Comet", "Halley", "Oort Cloud"],
  },
  {
    slug: "satellites",
    icon: "🛰",
    title: "Satellites",
    subtitle: "Orbital Observers",
    description: "Thousands of artificial satellites monitor Earth, relay communications, and explore space.",
    accent: "#34d399",
    glow: "rgba(52,211,153,0.35)",
    status: "~8,800 Active",
    statusColor: "#34d399",
    image: "/images/space-explorer/Satellite.png",
    tags: ["LEO", "GPS", "Communication"],
  },
  {
    slug: "spacecraft",
    icon: "🚀",
    title: "Spacecraft",
    subtitle: "Humanity's Reach",
    description: "Voyager, Hubble, JWST — the machines that extended our senses across the cosmos.",
    accent: "#60a5fa",
    glow: "rgba(96,165,250,0.35)",
    status: "Active Missions",
    statusColor: "#60a5fa",
    image: "/images/space-explorer/SpaceCraft.png",
    tags: ["Voyager", "JWST", "Probes"],
  },
  {
    slug: "earth-observation",
    icon: "🌍",
    title: "Earth Observation",
    subtitle: "Our Living Planet",
    description: "Satellite imagery, climate monitoring, and real-time data of our changing world.",
    accent: "#22c55e",
    glow: "rgba(34,197,94,0.35)",
    status: "Live Data",
    statusColor: "#22c55e",
    image: "/images/space-explorer/Satellite.png",
    tags: ["Climate", "Landsat", "EPIC"],
  },
  {
    slug: "space-weather",
    icon: "☀",
    title: "Space Weather",
    subtitle: "Solar Dynamics",
    description: "Solar flares, coronal mass ejections, and geomagnetic storms from our active Sun.",
    accent: "#fb923c",
    glow: "rgba(251,146,60,0.35)",
    status: "Real-time",
    statusColor: "#fb923c",
    image: "/images/space-explorer/SpaceWeather.png",
    tags: ["Solar Flares", "CME", "Aurora"],
  },
  {
    slug: "exoplanets",
    icon: "🌠",
    title: "Exoplanets",
    subtitle: "Worlds Beyond",
    description: "Over 5,700 confirmed worlds orbiting other stars — some potentially habitable.",
    accent: "#e879f9",
    glow: "rgba(232,121,249,0.35)",
    status: "5,700+ Confirmed",
    statusColor: "#e879f9",
    image: "/images/space-explorer/ExoPlanet.png",
    tags: ["Kepler", "TESS", "Habitable Zone"],
  },
  {
    slug: "stars",
    icon: "⭐",
    title: "Stars",
    subtitle: "Cosmic Furnaces",
    description: "From red dwarfs to blue supergiants — the nuclear furnaces powering the universe.",
    accent: "#fde68a",
    glow: "rgba(253,230,138,0.35)",
    status: "200B+ in Milky Way",
    statusColor: "#fde68a",
    image: "/images/space-explorer/Stars.png",
    tags: ["Main Sequence", "Supernovae", "Neutron Stars"],
  },
  {
    slug: "galaxies",
    icon: "🌌",
    title: "Galaxies",
    subtitle: "Island Universes",
    description: "Trillions of galaxies populate the observable universe, each containing billions of stars.",
    accent: "#818cf8",
    glow: "rgba(129,140,248,0.35)",
    status: "2T+ Estimated",
    statusColor: "#818cf8",
    image: "/images/space-explorer/Galaxies.png",
    tags: ["Milky Way", "Andromeda", "Clusters"],
  },
  {
    slug: "nebulae",
    icon: "🌌",
    title: "Nebulae",
    subtitle: "Stellar Nurseries",
    description: "Vast clouds of gas and dust — the birthplace and graveyard of stars.",
    accent: "#f472b6",
    glow: "rgba(244,114,182,0.35)",
    status: "Thousands Mapped",
    statusColor: "#f472b6",
    image: "/images/space-explorer/Nebulae.png",
    tags: ["Orion", "Pillars of Creation", "Planetary"],
  },
  {
    slug: "black-holes",
    icon: "⚫",
    title: "Black Holes",
    subtitle: "Gravity's Extreme",
    description: "Regions of spacetime where gravity is so intense that nothing — not even light — escapes.",
    accent: "#6366f1",
    glow: "rgba(99,102,241,0.35)",
    status: "M87* Imaged 2019",
    statusColor: "#6366f1",
    image: "/images/space-explorer/BlackHole.png",
    tags: ["Singularity", "Event Horizon", "Hawking"],
  },
  {
    slug: "astronomy-research",
    icon: "🧬",
    title: "Astronomy Research",
    subtitle: "Frontier Science",
    description: "Dark matter, gravitational waves, and the cosmic microwave background — the universe's deepest mysteries.",
    accent: "#2dd4bf",
    glow: "rgba(45,212,191,0.35)",
    status: "Active Research",
    statusColor: "#2dd4bf",
    image: "/images/space-explorer/Stars.png",
    tags: ["Dark Matter", "LIGO", "CMB"],
  },
  {
    slug: "nasa-missions",
    icon: "🚀",
    title: "NASA Missions",
    subtitle: "Exploration Legacy",
    description: "Apollo to Artemis — decades of missions defining humanity's presence in space.",
    accent: "#3b82f6",
    glow: "rgba(59,130,246,0.35)",
    status: "Active Programs",
    statusColor: "#3b82f6",
    image: "/images/space-explorer/NASA.png",
    tags: ["Apollo", "Artemis", "Mars 2020"],
  },
  {
    slug: "iss-tracker",
    icon: "🛰",
    title: "ISS Tracker",
    subtitle: "Live Position",
    description: "Track the International Space Station live as it orbits Earth every 90 minutes.",
    accent: "#38bdf8",
    glow: "rgba(56,189,248,0.35)",
    status: "Orbiting Now",
    statusColor: "#38bdf8",
    image: "/images/space-explorer/ISSTracker.png",
    tags: ["Live", "ISS", "Orbit"],
  },
  {
    slug: "earth-live",
    icon: "🌎",
    title: "Earth Live",
    subtitle: "Blue Marble",
    description: "Real-time NASA EPIC imagery of Earth's full disc from the DSCOVR satellite.",
    accent: "#4ade80",
    glow: "rgba(74,222,128,0.35)",
    status: "NASA EPIC",
    statusColor: "#4ade80",
    image: "/images/space-explorer/Satellite.png",
    tags: ["EPIC", "DSCOVR", "Real-time"],
  },
  {
    slug: "apod",
    icon: "📸",
    title: "Astronomy Picture of the Day",
    subtitle: "NASA APOD",
    description: "Each day a different image or photograph of our universe, explained by astronomers.",
    accent: "#c084fc",
    glow: "rgba(192,132,252,0.35)",
    status: "Daily Updated",
    statusColor: "#c084fc",
    image: "/images/space-explorer/NASA.png",
    tags: ["APOD", "Photography", "NASA"],
  },
  {
    slug: "mars-rover",
    icon: "🎥",
    title: "Mars Rover Gallery",
    subtitle: "Perseverance & Curiosity",
    description: "Latest photos beamed back from NASA's rovers exploring the Martian surface.",
    accent: "#f87171",
    glow: "rgba(248,113,113,0.35)",
    status: "Live Photos",
    statusColor: "#f87171",
    image: "/images/space-explorer/MarsRover.png",
    tags: ["Perseverance", "Curiosity", "Jezero"],
  },
  {
    slug: "neo",
    icon: "☄",
    title: "Near Earth Objects",
    subtitle: "Planetary Defense",
    description: "Asteroids and comets whose orbits bring them close to Earth — tracked daily by NASA.",
    accent: "#fb7185",
    glow: "rgba(251,113,133,0.35)",
    status: "Live NeoWs",
    statusColor: "#fb7185",
    image: "/images/space-explorer/NearEarthObject.png",
    tags: ["NEO", "Hazardous", "DART"],
  },
  {
    slug: "launches",
    icon: "🛸",
    title: "Launch Tracker",
    subtitle: "Global Rocket Launches",
    description: "Upcoming and recent rocket launches from every space agency worldwide, powered by Launch Library 2.",
    accent: "#34d399",
    glow: "rgba(52,211,153,0.35)",
    status: "Live Launches",
    statusColor: "#34d399",
    image: "/images/space-explorer/SpaceCraft.png",
    tags: ["Launches", "SpaceX", "ISRO", "Live"],
  },
  {
    slug: "spacex",
    icon: "🚀",
    title: "SpaceX",
    subtitle: "Commercial Space Leader",
    description: "Falcon 9, Starship, Dragon missions — the company that redefined commercial spaceflight.",
    accent: "#60a5fa",
    glow: "rgba(96,165,250,0.35)",
    status: "Active Missions",
    statusColor: "#60a5fa",
    image: "/images/space-explorer/SpaceCraft.png",
    tags: ["SpaceX", "Falcon 9", "Starship", "Missions"],
  },
];

export const SPACE_DETAIL: Record<string, SpaceDetailData> = {
  "solar-system": {
    slug: "solar-system",
    title: "Solar System",
    subtitle: "Our Cosmic Home",
    icon: "🪐",
    heroImage: "/images/planets/saturn.png",
    accent: "#f59e0b",
    overview:
      "Our Solar System formed approximately 4.6 billion years ago from a giant molecular cloud. The Sun contains 99.86% of all mass, while eight planets, 290+ moons, millions of asteroids, and billions of comets orbit within its gravitational influence. From the scorched rocky worlds of the inner system to the icy giants beyond the asteroid belt, each body tells a unique story of planetary formation.",
    stats: [
      { label: "Age", value: "4.6 Billion", unit: "Years" },
      { label: "Planets", value: "8" },
      { label: "Known Moons", value: "290+" },
      { label: "Diameter", value: "287.46 Billion", unit: "km" },
      { label: "Distance to Edge", value: "2 Light Years" },
      { label: "Speed Through Galaxy", value: "828,000", unit: "km/h" },
    ],
    facts: [
      "The Sun contains 99.86% of all the mass in the Solar System",
      "Jupiter is more than twice as massive as all other planets combined",
      "A day on Venus is longer than a year on Venus",
      "Saturn's rings are only about 10 meters thick on average",
      "Neptune's winds are the fastest in the solar system at 2,100 km/h",
      "There are more moons than planets — 290+ confirmed",
    ],
    timeline: [
      { year: "4.6 Byr ago", event: "Solar System Formation", detail: "Molecular cloud collapses to form the Sun and protoplanetary disk" },
      { year: "4.5 Byr ago", event: "Planet Formation", detail: "Rocky planets form through accretion in the inner system" },
      { year: "3.9 Byr ago", event: "Late Heavy Bombardment", detail: "Period of intense asteroid impacts on inner planets" },
      { year: "1610", event: "Galileo's Moons", detail: "Galileo discovers Jupiter's four largest moons" },
      { year: "1846", event: "Neptune Discovered", detail: "Neptune found through mathematical prediction" },
      { year: "2006", event: "Pluto Reclassified", detail: "IAU reclassifies Pluto as a dwarf planet" },
    ],
    missions: [
      { name: "Voyager 1", agency: "NASA", status: "Active", year: "1977", description: "Now in interstellar space, still transmitting data" },
      { name: "New Horizons", agency: "NASA", status: "Active", year: "2006", description: "Explored Pluto and Arrokoth in the Kuiper Belt" },
      { name: "Cassini-Huygens", agency: "NASA/ESA", status: "Completed", year: "1997", description: "13 years orbiting Saturn, revolutionizing our understanding" },
      { name: "Juno", agency: "NASA", status: "Active", year: "2011", description: "Currently orbiting Jupiter, studying its atmosphere and interior" },
    ],
    gallery: [
      { src: "/images/planets/saturn.png", caption: "Saturn with its majestic ring system" },
      { src: "/images/planets/jupiter.png", caption: "Jupiter's banded atmosphere" },
      { src: "/images/planets/mars.png", caption: "Mars, the Red Planet" },
      { src: "/images/planets/earth.png", caption: "Earth, our pale blue dot" },
    ],
    relatedSlugs: ["dwarf-planets", "asteroids", "comets", "nasa-missions"],
    aiPrompts: [
      "How did the Solar System form?",
      "What is the most massive planet?",
      "Could life exist elsewhere in our solar system?",
      "What lies beyond Neptune?",
    ],
    apiSource: "NASA Solar System Exploration",
  },
  "earth": {
    slug: "earth",
    title: "Earth",
    subtitle: "The Blue Marble",
    icon: "🌍",
    heroImage: "/images/planets/earth.png",
    accent: "#55aaff",
    overview: "Earth is the third planet from the Sun and the only known astronomical object to harbour life. With liquid water covering 71% of its surface, a protective magnetic field, and a nitrogen-oxygen atmosphere, Earth is uniquely suited for life. Our planet is tectonically active, with continuously moving plates that shape continents and drive volcanism.",
    stats: [
      { label: "Diameter", value: "12,742", unit: "km" },
      { label: "Mass", value: "5.972 × 10²⁴", unit: "kg" },
      { label: "Gravity", value: "9.81", unit: "m/s²" },
      { label: "Distance from Sun", value: "149.6 Million", unit: "km" },
      { label: "Day Length", value: "23h 56m" },
      { label: "Moons", value: "1" },
      { label: "Water Coverage", value: "71", unit: "%" },
      { label: "Atmosphere", value: "78% N₂, 21% O₂" },
    ],
    facts: [
      "Earth is the densest planet in the Solar System",
      "The Moon is slowly drifting away from Earth at 3.8 cm per year",
      "Earth's inner core is as hot as the surface of the Sun (~5,700°C)",
      "Only planet where plate tectonics have been confirmed",
      "The Amazon rainforest produces 20% of the world's oxygen",
      "Earth's magnetic field protects us from harmful solar radiation",
    ],
    timeline: [
      { year: "4.54 Byr ago", event: "Earth Forms", detail: "Accretion from the protoplanetary disk" },
      { year: "4.5 Byr ago", event: "Moon Formation", detail: "Giant impact creates the Moon" },
      { year: "3.8 Byr ago", event: "First Life", detail: "Earliest microbial life appears in oceans" },
      { year: "541 Myr ago", event: "Cambrian Explosion", detail: "Rapid diversification of multicellular life" },
      { year: "1957", event: "Space Age Begins", detail: "Sputnik 1 becomes first artificial satellite" },
      { year: "1972", event: "Blue Marble Photo", detail: "Apollo 17 captures iconic Earth photograph" },
    ],
    missions: [
      { name: "ISS", agency: "NASA/Roscosmos/ESA/JAXA/CSA", status: "Active", year: "1998", description: "Continuously crewed orbital laboratory since 2000" },
      { name: "Landsat 9", agency: "NASA/USGS", status: "Active", year: "2021", description: "Earth observation for land-use change detection" },
      { name: "Sentinel-6", agency: "ESA/NASA", status: "Active", year: "2020", description: "Sea level monitoring with millimetre precision" },
      { name: "DSCOVR", agency: "NOAA/NASA", status: "Active", year: "2015", description: "Full-disc Earth imagery and space weather monitoring" },
    ],
    gallery: [
      { src: "/images/planets/earth.png", caption: "Earth from space" },
    ],
    relatedSlugs: ["earth-observation", "satellites", "iss-tracker", "earth-live"],
    aiPrompts: [
      "Why is Earth the only known planet with life?",
      "How does Earth's magnetic field work?",
      "What would happen if Earth stopped rotating?",
      "How are humans changing Earth's climate?",
    ],
    apiSource: "NASA EPIC API",
  },
  "mars": {
    slug: "mars",
    title: "Mars",
    subtitle: "The Red Planet",
    icon: "🔴",
    heroImage: "/images/planets/mars.png",
    accent: "#e05020",
    overview: "Mars is the fourth planet from the Sun and the second-smallest in the Solar System. Its reddish appearance comes from iron oxide (rust) on its surface. Mars hosts the tallest volcano in the solar system — Olympus Mons at 21 km — and the longest canyon — Valles Marineris at 4,000 km. Evidence of ancient river valleys and lake beds suggests Mars once had liquid water.",
    stats: [
      { label: "Diameter", value: "6,779", unit: "km" },
      { label: "Gravity", value: "3.71", unit: "m/s²" },
      { label: "Distance from Sun", value: "227.9 Million", unit: "km" },
      { label: "Day Length", value: "24h 37m" },
      { label: "Year Length", value: "687", unit: "Earth Days" },
      { label: "Moons", value: "2 (Phobos & Deimos)" },
      { label: "Temp", value: "-63°C", unit: "Average" },
      { label: "Atmosphere", value: "95% CO₂" },
    ],
    facts: [
      "Olympus Mons is 3× the height of Mount Everest",
      "Valles Marineris is as long as the continental US",
      "Mars has the largest dust storms in the solar system",
      "A Martian day (sol) is 24 hours and 37 minutes",
      "Mars has two small moons, Phobos and Deimos",
      "Perseverance rover has produced oxygen from Martian CO₂",
    ],
    timeline: [
      { year: "1877", event: "Moons Discovered", detail: "Asaph Hall discovers Phobos and Deimos" },
      { year: "1965", event: "Mariner 4", detail: "First close-up images of Mars from NASA flyby" },
      { year: "1976", event: "Viking Landers", detail: "First successful Mars surface missions" },
      { year: "1997", event: "Mars Pathfinder", detail: "Sojourner rover operates on Mars surface" },
      { year: "2004", event: "Spirit & Opportunity", detail: "Twin rovers land, Opportunity lasts 15 years" },
      { year: "2021", event: "Perseverance Lands", detail: "Most sophisticated rover lands in Jezero Crater" },
    ],
    missions: [
      { name: "Perseverance", agency: "NASA", status: "Active", year: "2021", description: "Collecting rock samples for future return to Earth" },
      { name: "Curiosity", agency: "NASA", status: "Active", year: "2012", description: "Exploring Gale Crater for signs of ancient habitability" },
      { name: "Ingenuity", agency: "NASA", status: "Completed", year: "2021", description: "First powered flight on another planet — 72 flights total" },
      { name: "Mars Reconnaissance Orbiter", agency: "NASA", status: "Active", year: "2006", description: "High-resolution imaging from orbit" },
    ],
    gallery: [
      { src: "/images/planets/mars.png", caption: "Mars from orbit" },
    ],
    relatedSlugs: ["mars-rover", "nasa-missions", "spacecraft", "asteroids"],
    aiPrompts: [
      "Can humans live on Mars?",
      "What is Olympus Mons?",
      "What did Perseverance discover?",
      "Why is Mars red?",
    ],
    apiSource: "NASA Mars Rover Photos API",
  },
};

// Fill in remaining slugs with generated data (only those not yet defined)
const REMAINING_SLUGS = ["satellites", "spacecraft"];

REMAINING_SLUGS.forEach((slug) => {
  if (!SPACE_DETAIL[slug]) {
    const cat = SPACE_CATEGORIES.find((c) => c.slug === slug)!;
    SPACE_DETAIL[slug] = {
      slug,
      title: cat.title,
      subtitle: cat.subtitle,
      icon: cat.icon,
      heroImage: cat.image,
      accent: cat.accent,
      overview: cat.description,
      stats: [],
      facts: [],
      timeline: [],
      missions: [],
      gallery: [{ src: cat.image, caption: cat.title }],
      relatedSlugs: [],
      aiPrompts: [`Tell me about ${cat.title}`, `What is interesting about ${cat.title}?`],
    };
  }
});

// ── Rich detail for all content slugs ────────────────────────────────────────

SPACE_DETAIL["dwarf-planets"] = {
  slug: "dwarf-planets",
  title: "Dwarf Planets",
  subtitle: "Beyond Neptune",
  icon: "🌠",
  heroImage: "/images/space-explorer/DwarfPlanets.png",
  accent: "#a78bfa",
  overview: "Dwarf planets are solar system bodies that orbit the Sun, have enough mass for gravity to make them nearly round, but have not cleared the neighbourhood around their orbits. The IAU currently recognises five: Pluto, Eris, Haumea, Makemake, and Ceres. Hundreds more likely exist in the outer solar system's Kuiper Belt and Oort Cloud.",
  stats: [
    { label: "IAU-recognised", value: "5", unit: "Dwarf Planets" },
    { label: "Pluto Diameter", value: "2,377", unit: "km" },
    { label: "Eris Mass", value: "27% more", unit: "than Pluto" },
    { label: "Ceres Location", value: "Asteroid Belt" },
    { label: "Pluto Moons", value: "5 (Charon, Nix, Hydra…)" },
    { label: "Pluto Distance", value: "5.9 Billion", unit: "km from Sun" },
  ],
  facts: [
    "Pluto was considered the 9th planet for 76 years before being reclassified in 2006",
    "Charon is so large relative to Pluto that the pair is considered a double dwarf planet",
    "Eris is slightly more massive than Pluto despite being similar in size",
    "Ceres is the only dwarf planet in the inner solar system and the asteroid belt",
    "New Horizons revealed Pluto has mountains of water ice up to 3,500 m tall",
    "Pluto's surface features a nitrogen glacier — the famous heart-shaped Tombaugh Regio",
  ],
  timeline: [
    { year: "1930", event: "Pluto Discovered", detail: "Clyde Tombaugh discovers Pluto at Lowell Observatory" },
    { year: "1977", event: "Charon Found", detail: "Pluto's largest moon Charon is discovered" },
    { year: "2005", event: "Eris Discovered", detail: "Eris found beyond the Kuiper Belt — larger than Pluto" },
    { year: "2006", event: "IAU Reclassification", detail: "Pluto, Eris and Ceres formally classified as dwarf planets" },
    { year: "2015", event: "New Horizons Flyby", detail: "First close-up images of Pluto's heart and mountains" },
    { year: "2022", event: "Dawn at Ceres", detail: "Ongoing study of Ceres' bright spots (brine deposits)" },
  ],
  missions: [
    { name: "New Horizons", agency: "NASA", status: "Active", year: "2006", description: "Flew past Pluto in 2015, now in Kuiper Belt extended mission" },
    { name: "Dawn", agency: "NASA", status: "Completed", year: "2007", description: "Orbited Ceres and Vesta — revealed bright brine deposits on Ceres" },
  ],
  gallery: [{ src: "/images/space-explorer/DwarfPlanets.png", caption: "Pluto — the first dwarf planet visited by spacecraft" }],
  relatedSlugs: ["solar-system", "asteroids", "comets"],
  aiPrompts: ["Why was Pluto reclassified?", "How many dwarf planets are there?", "What did New Horizons find on Pluto?", "What is the Kuiper Belt?"],
};

SPACE_DETAIL["asteroids"] = {
  slug: "asteroids",
  title: "Asteroids",
  subtitle: "Rocky Remnants",
  icon: "☄",
  heroImage: "/images/space-explorer/Asteroid.png",
  accent: "#94a3b8",
  overview: "Asteroids are rocky, airless remnants left over from the early formation of our solar system about 4.6 billion years ago. Most reside in the asteroid belt between Mars and Jupiter. They range in size from Vesta at ~525 km across, to particles smaller than a metre. Near-Earth Asteroids (NEAs) are those whose orbits bring them within 1.3 AU of the Sun.",
  stats: [
    { label: "Known Asteroids", value: "1.1 Million+" },
    { label: "Largest: Ceres", value: "940", unit: "km diameter" },
    { label: "Vesta Diameter", value: "~525", unit: "km" },
    { label: "Near-Earth Asteroids", value: "33,000+" },
    { label: "Asteroid Belt Width", value: "~2.2–3.2", unit: "AU" },
    { label: "DART Impact Speed", value: "6.1", unit: "km/s" },
  ],
  facts: [
    "The DART mission in 2022 successfully deflected asteroid Dimorphos — proving planetary defence is possible",
    "Ceres accounts for about 33% of the total mass of the asteroid belt",
    "Most asteroids are primitive C-type (carbonaceous), S-type (silicate), or M-type (metallic)",
    "Apophis will pass within 32,000 km of Earth in 2029 — closer than geostationary satellites",
    "OSIRIS-REx returned a 121-gram sample from asteroid Bennu to Earth in 2023",
    "The asteroid belt is mostly empty space — the gap between asteroids averages 1 million km",
  ],
  timeline: [
    { year: "1801", event: "Ceres Discovered", detail: "Giuseppe Piazzi discovers first and largest asteroid" },
    { year: "1898", event: "Eros Discovered", detail: "First near-Earth asteroid found" },
    { year: "2001", event: "NEAR Shoemaker", detail: "First spacecraft to land on an asteroid (Eros)" },
    { year: "2010", event: "Hayabusa Returns", detail: "JAXA returns first asteroid sample from Itokawa" },
    { year: "2022", event: "DART Impact", detail: "NASA deflects Dimorphos — first planetary defence test" },
    { year: "2023", event: "Bennu Sample", detail: "OSIRIS-REx delivers Bennu sample to Earth" },
  ],
  missions: [
    { name: "OSIRIS-REx / OSIRIS-APEX", agency: "NASA", status: "Active", year: "2016", description: "Returned Bennu sample; now en route to Apophis (arrives 2029)" },
    { name: "Hayabusa 2", agency: "JAXA", status: "Active", year: "2014", description: "Returned samples from asteroid Ryugu in 2020; extended mission ongoing" },
    { name: "Lucy", agency: "NASA", status: "Active", year: "2021", description: "First mission to Jupiter's Trojan asteroids (2025–2033 flybys)" },
    { name: "DART", agency: "NASA", status: "Completed", year: "2021", description: "Successfully deflected Dimorphos in Sept 2022" },
  ],
  gallery: [{ src: "/images/space-explorer/Asteroid.png", caption: "Asteroid Bennu imaged by OSIRIS-REx" }],
  relatedSlugs: ["neo", "comets", "solar-system"],
  aiPrompts: ["What is the DART mission?", "Will Apophis hit Earth?", "What are near-Earth asteroids?", "What was found in the Bennu sample?"],
};

SPACE_DETAIL["comets"] = {
  slug: "comets",
  title: "Comets",
  subtitle: "Icy Wanderers",
  icon: "☄",
  heroImage: "/images/space-explorer/Comet.png",
  accent: "#67e8f9",
  overview: "Comets are icy small solar system bodies that, when passing close to the Sun, warm and begin to release gases — a process called outgassing. This produces a visible atmosphere (coma) and often two tails: an ion tail always pointing away from the Sun, and a dust tail curving along the comet's orbit. Most originate in the Oort Cloud or Kuiper Belt.",
  stats: [
    { label: "Known Comets", value: "3,700+", unit: "catalogued" },
    { label: "Halley Period", value: "~75–76", unit: "years" },
    { label: "Rosetta Mission", value: "67P/C-G", unit: "target comet" },
    { label: "Comet Tail Length", value: "Up to 1", unit: "AU (150M km)" },
    { label: "Nucleus Size", value: "100m–40km", unit: "typical range" },
    { label: "Comet NEOWISE", value: "2020", unit: "last naked-eye comet" },
  ],
  facts: [
    "Halley's Comet has been observed since 240 BCE — its next apparition is in 2061",
    "The Rosetta mission landed a probe (Philae) on comet 67P — first ever soft comet landing",
    "Comets may have delivered water and organic molecules to early Earth",
    "Comet tails always point away from the Sun, driven by solar wind",
    "Comet NEOWISE in 2020 was the brightest comet visible to the naked eye in 23 years",
    "Short-period comets originate in the Kuiper Belt; long-period ones come from the Oort Cloud",
  ],
  timeline: [
    { year: "1705", event: "Halley's Prediction", detail: "Edmond Halley calculates the comet's 76-year orbit period" },
    { year: "1986", event: "Halley Visited", detail: "Giotto spacecraft passes within 600 km of Halley's nucleus" },
    { year: "2005", event: "Deep Impact", detail: "NASA deliberately impacts comet Tempel 1 to study interior" },
    { year: "2014", event: "Rosetta Arrives", detail: "ESA's Rosetta spacecraft enters orbit around comet 67P" },
    { year: "2016", event: "Rosetta End", detail: "Rosetta mission ends with controlled impact on 67P" },
    { year: "2025", event: "Comet C/2023 A3", detail: "Tsuchinshan–ATLAS briefly visible in late 2024" },
  ],
  missions: [
    { name: "Rosetta / Philae", agency: "ESA", status: "Completed", year: "2004", description: "First spacecraft to orbit a comet and land a probe on its surface (67P)" },
    { name: "Deep Impact", agency: "NASA", status: "Completed", year: "2005", description: "Impacted comet Tempel 1 to expose pristine interior material" },
    { name: "Stardust", agency: "NASA", status: "Completed", year: "1999", description: "Collected comet Wild 2 particles and returned them to Earth in 2006" },
  ],
  gallery: [{ src: "/images/space-explorer/Comet.png", caption: "Comet 67P/Churyumov–Gerasimenko imaged by Rosetta" }],
  relatedSlugs: ["asteroids", "solar-system", "dwarf-planets"],
  aiPrompts: ["When is Halley's comet next visible?", "What did Rosetta discover?", "How are comets different from asteroids?", "Could a comet hit Earth?"],
};

SPACE_DETAIL["earth-observation"] = {
  slug: "earth-observation",
  title: "Earth Observation",
  subtitle: "Our Living Planet",
  icon: "🌍",
  heroImage: "/images/space-explorer/Satellite.png",
  accent: "#22c55e",
  overview: "Earth observation satellites monitor our planet continuously — tracking climate change, deforestation, sea level rise, urban growth, and natural disasters. NASA's fleet includes Landsat (land use), GRACE (gravity/groundwater), and the DSCOVR/EPIC camera that provides daily full-disc Earth imagery. The EU's Copernicus Sentinel programme adds millimetre-precision radar mapping.",
  stats: [
    { label: "Earth Observation Satellites", value: "1,000+", unit: "Active" },
    { label: "Landsat Archive", value: "50+ Years", unit: "of imagery" },
    { label: "DSCOVR Location", value: "L1 Lagrange", unit: "Point" },
    { label: "EPIC Full-disc Images", value: "Daily", unit: "updates" },
    { label: "Sea Level Rise Rate", value: "3.3", unit: "mm/year" },
    { label: "Copernicus Satellites", value: "7 Sentinel", unit: "spacecraft" },
  ],
  facts: [
    "The Copernicus Programme provides the most comprehensive Earth monitoring data ever collected",
    "Landsat has captured over 10 million scenes since 1972 — the longest continuous land record",
    "GRACE detected groundwater depletion under California's Central Valley from orbit",
    "NASA's MODIS satellite detects wildfires within 3 hours of ignition",
    "Sentinel-6 measures global sea level with millimetre precision",
    "The DSCOVR satellite at L1 sees the full sunlit face of Earth every day",
  ],
  timeline: [
    { year: "1972", event: "Landsat 1", detail: "First Earth resources satellite begins continuous land observation" },
    { year: "1999", event: "Terra Launched", detail: "NASA's flagship Earth observing satellite begins operations" },
    { year: "2002", event: "Aqua Launched", detail: "Monitors water cycle and ocean temperatures" },
    { year: "2015", event: "DSCOVR / EPIC", detail: "Daily full-disc Earth imagery from the L1 point" },
    { year: "2016", event: "Sentinel-2", detail: "Copernicus high-res multispectral Earth imaging begins" },
    { year: "2022", event: "SWOT Launched", detail: "Surface Water and Ocean Topography — first global water map" },
  ],
  missions: [
    { name: "Landsat 9", agency: "NASA/USGS", status: "Active", year: "2021", description: "Continuity of 50-year Earth land observation record" },
    { name: "DSCOVR", agency: "NOAA/NASA", status: "Active", year: "2015", description: "Full Earth disc EPIC imagery + space weather monitoring from L1" },
    { name: "Sentinel-6 Michael Freilich", agency: "ESA/NASA/EUMETSAT", status: "Active", year: "2020", description: "Sea level altimetry with millimetre-level precision" },
    { name: "SWOT", agency: "NASA/CNES", status: "Active", year: "2022", description: "First global survey of Earth's surface water" },
  ],
  gallery: [{ src: "/images/space-explorer/Satellite.png", caption: "Earth observation — watching our planet from orbit" }],
  relatedSlugs: ["earth-live", "iss-tracker", "satellites", "space-weather"],
  aiPrompts: ["What is NASA EPIC?", "How do satellites track climate change?", "What is the Landsat programme?", "How is sea level rise measured from space?"],
};

SPACE_DETAIL["stars"] = {
  slug: "stars",
  title: "Stars",
  subtitle: "Cosmic Furnaces",
  icon: "⭐",
  heroImage: "/images/space-explorer/Stars.png",
  accent: "#fde68a",
  overview: "Stars are massive, luminous spheres of plasma held together by gravity, powered by nuclear fusion in their cores. They fuse hydrogen into helium — releasing enormous energy as light and heat. Our Sun is a middle-aged G-type main-sequence star. Stars range from cool red dwarfs (the most common) to blazing blue supergiants 100× the Sun's mass. At the end of their lives, stars produce supernovae, neutron stars, and black holes.",
  stats: [
    { label: "Stars in Milky Way", value: "200–400 Billion", unit: "estimated" },
    { label: "Nearest Star", value: "4.2", unit: "light-years (Proxima)" },
    { label: "Sun's Age", value: "4.6 Billion", unit: "years" },
    { label: "Sun's Core Temp", value: "15 Million", unit: "°C" },
    { label: "Betelgeuse Diameter", value: "700× ", unit: "the Sun" },
    { label: "Most Common Type", value: "Red Dwarf", unit: "(M-class)" },
  ],
  facts: [
    "Neutron stars can spin over 700 times per second — faster than a kitchen blender",
    "Betelgeuse is so large it would swallow Mercury, Venus, Earth, Mars, and the asteroid belt",
    "The Sun converts 600 million tonnes of hydrogen into helium every second",
    "About 85% of stars in the Milky Way are red dwarfs — too faint to see with the naked eye",
    "A teaspoon of neutron star material weighs about a billion tonnes",
    "Stars form in nebulae — dense clouds of gas and dust that collapse under gravity",
  ],
  timeline: [
    { year: "1609", event: "Galileo's Telescope", detail: "First telescopic observations revealing stars as distant suns" },
    { year: "1838", event: "Stellar Parallax", detail: "Friedrich Bessel first measures the distance to a star (61 Cygni)" },
    { year: "1910", event: "H-R Diagram", detail: "Hertzsprung-Russell diagram classifies stars by temperature and luminosity" },
    { year: "1967", event: "Pulsar Discovered", detail: "Jocelyn Bell discovers first pulsar — a rotating neutron star" },
    { year: "2019", event: "Betelgeuse Dims", detail: "Great Dimming event prompts global study of supergiant variability" },
    { year: "2022", event: "Earendel Record", detail: "JWST observes most distant individual star — 28 billion light-years away" },
  ],
  missions: [
    { name: "James Webb Space Telescope", agency: "NASA/ESA/CSA", status: "Active", year: "2021", description: "Studies stellar formation and the earliest stars in the universe" },
    { name: "Gaia", agency: "ESA", status: "Active", year: "2013", description: "Mapped 1.8 billion stars with unprecedented position precision" },
    { name: "TESS", agency: "NASA", status: "Active", year: "2018", description: "All-sky survey finding planets around nearby bright stars" },
    { name: "Kepler Space Telescope", agency: "NASA", status: "Completed", year: "2009", description: "Discovered 2,600+ exoplanets by monitoring stellar brightness" },
  ],
  gallery: [{ src: "/images/space-explorer/Stars.png", caption: "The Orion Nebula — a stellar nursery 1,344 light-years away" }],
  relatedSlugs: ["galaxies", "black-holes", "nebulae", "astronomy-research"],
  aiPrompts: ["How do stars form?", "What happens when a star dies?", "What is a neutron star?", "How far away is the nearest star?", "Will the Sun become a black hole?"],
};

SPACE_DETAIL["galaxies"] = {
  slug: "galaxies",
  title: "Galaxies",
  subtitle: "Island Universes",
  icon: "🌌",
  heroImage: "/images/space-explorer/Galaxies.png",
  accent: "#818cf8",
  overview: "Galaxies are vast gravitationally bound systems containing stars, gas, dust, dark matter, and black holes. The observable universe contains an estimated two trillion galaxies. Our Milky Way is a barred spiral galaxy roughly 100,000 light-years across, containing 200–400 billion stars. The nearest large galaxy — Andromeda (M31) — is on a collision course with the Milky Way, arriving in about 4.5 billion years.",
  stats: [
    { label: "Observable Universe Galaxies", value: "~2 Trillion", unit: "estimated" },
    { label: "Milky Way Diameter", value: "100,000", unit: "light-years" },
    { label: "Milky Way Stars", value: "200–400 Billion" },
    { label: "Distance to Andromeda", value: "2.537 Million", unit: "light-years" },
    { label: "Milky Way Central BH", value: "Sagittarius A*", unit: "4M solar masses" },
    { label: "Largest Known Galaxy", value: "IC 1101", unit: "6M light-years across" },
  ],
  facts: [
    "Andromeda and the Milky Way will merge in ~4.5 billion years — creating 'Milkomeda'",
    "The Milky Way bar structure at its centre is about 27,000 light-years long",
    "Dwarf galaxies orbiting the Milky Way include the Large and Small Magellanic Clouds",
    "Galaxy NGC 1277 has a black hole containing 59% of its total mass",
    "The Hubble Ultra Deep Field revealed ~10,000 galaxies in a patch of sky the size of a grain of sand held at arm's length",
    "Dark matter makes up ~85% of the total mass in a typical galaxy",
  ],
  timeline: [
    { year: "1610", event: "Andromeda Observed", detail: "Simon Marius first describes the Andromeda Nebula" },
    { year: "1923", event: "Galaxies Confirmed", detail: "Edwin Hubble proves Andromeda is a separate galaxy beyond the Milky Way" },
    { year: "1929", event: "Universe Expanding", detail: "Hubble discovers galaxies are moving away — proving cosmic expansion" },
    { year: "1965", event: "CMB Discovered", detail: "Cosmic Microwave Background confirms Big Bang origin of galaxies" },
    { year: "1995", event: "Hubble Deep Field", detail: "3,000 galaxies revealed in a tiny dark patch of sky" },
    { year: "2022", event: "JWST First Images", detail: "Deepest infrared view shows galaxies from just 300M years after Big Bang" },
  ],
  missions: [
    { name: "James Webb Space Telescope", agency: "NASA/ESA/CSA", status: "Active", year: "2021", description: "Observing the first galaxies that formed after the Big Bang" },
    { name: "Hubble Space Telescope", agency: "NASA/ESA", status: "Active", year: "1990", description: "Mapped galaxy evolution across cosmic time with the Hubble Deep Fields" },
    { name: "Euclid", agency: "ESA", status: "Active", year: "2023", description: "Dark energy survey — mapping 1 billion galaxies across 10 billion years" },
    { name: "Roman Space Telescope", agency: "NASA", status: "Upcoming", year: "2026", description: "Wide-field survey of galaxy distribution and dark energy" },
  ],
  gallery: [{ src: "/images/space-explorer/Galaxies.png", caption: "The Andromeda Galaxy — our nearest large galactic neighbour" }],
  relatedSlugs: ["black-holes", "stars", "nebulae", "astronomy-research"],
  aiPrompts: ["What is the Milky Way?", "Will Andromeda collide with us?", "How many galaxies exist?", "What is dark matter in galaxies?", "What did JWST reveal about early galaxies?"],
};

SPACE_DETAIL["nebulae"] = {
  slug: "nebulae",
  title: "Nebulae",
  subtitle: "Stellar Nurseries",
  icon: "🌌",
  heroImage: "/images/space-explorer/Nebulae.png",
  accent: "#f472b6",
  overview: "Nebulae are vast interstellar clouds of gas and dust — the birthplaces and graveyards of stars. Emission nebulae glow as ionised hydrogen is excited by nearby hot stars. Reflection nebulae scatter blue starlight. Dark nebulae block background light. Planetary nebulae are the expelled shells of dying stars. Supernova remnants are the debris from stellar explosions. The James Webb Space Telescope has revealed unprecedented detail within them.",
  stats: [
    { label: "Orion Nebula Distance", value: "1,344", unit: "light-years" },
    { label: "Pillars of Creation", value: "~6,500", unit: "light-years away" },
    { label: "Crab Nebula Age", value: "~970", unit: "years (SN 1054)" },
    { label: "Orion Nebula Diameter", value: "~40", unit: "light-years" },
    { label: "Helix Nebula Distance", value: "650", unit: "light-years" },
    { label: "Eagle Nebula Width", value: "~70", unit: "light-years" },
  ],
  facts: [
    "The Pillars of Creation in the Eagle Nebula were imaged by both Hubble (1995) and JWST (2022)",
    "The Orion Nebula is the nearest large star-forming region — visible to the naked eye",
    "The Crab Nebula is the remnant of a supernova observed by Chinese astronomers in 1054 AD",
    "Planetary nebulae have nothing to do with planets — Herschel just thought they looked like planets",
    "JWST's 2022 image of the Carina Nebula revealed hundreds of previously hidden protostars",
    "Our Sun will eventually form a planetary nebula in about 5 billion years",
  ],
  timeline: [
    { year: "1054", event: "Crab Nebula Supernova", detail: "Chinese astronomers record the SN that produced the Crab Nebula" },
    { year: "1784", event: "Nebula Catalogues", detail: "Messier catalogue lists 40+ nebulae and star clusters" },
    { year: "1923", event: "Nature Resolved", detail: "Hubble resolves Andromeda as a galaxy, not a nebula" },
    { year: "1995", event: "Pillars of Creation", detail: "Hubble photographs the iconic Eagle Nebula pillars" },
    { year: "2022", event: "JWST Nebulae", detail: "Webb reveals the Carina and Southern Ring nebulae in unprecedented detail" },
  ],
  missions: [
    { name: "James Webb Space Telescope", agency: "NASA/ESA/CSA", status: "Active", year: "2021", description: "Infrared observation penetrates dust to reveal hidden star formation" },
    { name: "Hubble Space Telescope", agency: "NASA/ESA", status: "Active", year: "1990", description: "Iconic nebula images including Pillars of Creation and Eta Carinae" },
    { name: "Spitzer Space Telescope", agency: "NASA", status: "Completed", year: "2003", description: "Infrared survey revealed embedded star formation in dark nebulae" },
  ],
  gallery: [{ src: "/images/space-explorer/Nebulae.png", caption: "The Eagle Nebula's Pillars of Creation — birthplace of new stars" }],
  relatedSlugs: ["stars", "galaxies", "black-holes", "astronomy-research"],
  aiPrompts: ["What are the Pillars of Creation?", "What is the Orion Nebula?", "How do stars form in nebulae?", "What did JWST reveal about nebulae?"],
};

SPACE_DETAIL["astronomy-research"] = {
  slug: "astronomy-research",
  title: "Astronomy Research",
  subtitle: "Frontier Science",
  icon: "🧬",
  heroImage: "/images/space-explorer/Stars.png",
  accent: "#2dd4bf",
  overview: "Modern astronomy probes the universe's deepest mysteries — dark matter, dark energy, gravitational waves, and the cosmic microwave background. Facilities like LIGO, the Event Horizon Telescope, and JWST have produced transformative discoveries in recent years. The universe is 13.8 billion years old, yet 95% of its content (dark matter and dark energy) remains unexplained.",
  stats: [
    { label: "Universe Age", value: "13.8 Billion", unit: "years" },
    { label: "Dark Energy", value: "68", unit: "% of universe" },
    { label: "Dark Matter", value: "27", unit: "% of universe" },
    { label: "Observable Universe Diameter", value: "93 Billion", unit: "light-years" },
    { label: "Gravitational Wave Events", value: "90+", unit: "detected by LIGO/Virgo" },
    { label: "CMB Temperature", value: "2.725", unit: "K" },
  ],
  facts: [
    "LIGO first detected gravitational waves on 14 September 2015 — a century after Einstein predicted them",
    "The cosmic microwave background is the afterglow of the Big Bang, still visible as microwave radiation",
    "Dark energy is causing the expansion of the universe to accelerate — discovered in 1998",
    "The Event Horizon Telescope is effectively an Earth-sized telescope imaging black holes",
    "Neutrino astronomy opened a new window on the universe — IceCube detected the first high-energy cosmic neutrinos",
    "The Hubble Constant tension — two independent measurements disagree, potentially requiring new physics",
  ],
  timeline: [
    { year: "1965", event: "CMB Discovered", detail: "Penzias and Wilson accidentally detect the cosmic microwave background" },
    { year: "1998", event: "Dark Energy", detail: "Supernova surveys show the universe's expansion is accelerating" },
    { year: "2015", event: "Gravitational Waves", detail: "LIGO detects first gravitational wave signal from merging black holes" },
    { year: "2019", event: "Black Hole Imaged", detail: "Event Horizon Telescope images M87* shadow for the first time" },
    { year: "2022", event: "Sgr A* Imaged", detail: "EHT images the Milky Way's central black hole Sagittarius A*" },
    { year: "2023", event: "Gravitational Wave Background", detail: "Pulsar timing arrays detect a stochastic gravitational wave background" },
  ],
  missions: [
    { name: "James Webb Space Telescope", agency: "NASA/ESA/CSA", status: "Active", year: "2021", description: "Probing earliest galaxies, dark matter via gravitational lensing, exoplanet atmospheres" },
    { name: "Euclid", agency: "ESA", status: "Active", year: "2023", description: "3D map of the universe to constrain dark energy and dark matter" },
    { name: "LIGO / Virgo / KAGRA", agency: "NSF/EU/NAOJ", status: "Active", year: "2015", description: "Gravitational wave interferometers detecting merging black holes and neutron stars" },
    { name: "Event Horizon Telescope", agency: "International", status: "Active", year: "2017", description: "Earth-spanning radio telescope imaging black hole shadows" },
    { name: "Square Kilometre Array", agency: "International", status: "Upcoming", year: "2027", description: "World's largest radio telescope for cosmic magnetism, dark energy, and pulsars" },
  ],
  gallery: [{ src: "/images/space-explorer/Stars.png", caption: "The frontier of astrophysics — dark matter, gravitational waves, and beyond" }],
  relatedSlugs: ["black-holes", "galaxies", "stars", "exoplanets"],
  aiPrompts: ["What is dark matter?", "What are gravitational waves?", "What is the cosmic microwave background?", "What is the Hubble tension?", "What did LIGO discover?"],
};

SPACE_DETAIL["nasa-missions"] = {
  slug: "nasa-missions",
  title: "NASA Missions",
  subtitle: "Exploration Legacy",
  icon: "🚀",
  heroImage: "/images/space-explorer/NASA.png",
  accent: "#3b82f6",
  overview: "NASA's 65-year history of space exploration spans humanity's first steps on the Moon to robotic pioneers at the edge of the solar system. From Apollo to Artemis, from Voyager to JWST, NASA missions have defined our understanding of Earth, the solar system, and the cosmos. The Artemis programme is returning humans to the Moon with the goal of establishing a permanent lunar presence and eventually reaching Mars.",
  stats: [
    { label: "Founded", value: "October 1, 1958" },
    { label: "Crewed Lunar Landings", value: "6", unit: "(Apollo 11–17)" },
    { label: "Active Missions", value: "100+", unit: "as of 2025" },
    { label: "Mars Rovers", value: "5", unit: "deployed total" },
    { label: "Artemis Target", value: "South Pole", unit: "of the Moon" },
    { label: "Annual Budget", value: "~$25", unit: "Billion (FY2025)" },
  ],
  facts: [
    "Apollo 17 (1972) remains the last time humans walked on the Moon",
    "Voyager 1 is the only human-made object in interstellar space",
    "The Hubble Space Telescope has made over 1.5 million observations since 1990",
    "NASA's Mars rovers have collectively driven over 100 km on the Martian surface",
    "Artemis II will fly astronauts around the Moon in 2026 — first crewed lunar mission since Apollo",
    "The ISS has been continuously inhabited since November 2, 2000",
  ],
  timeline: [
    { year: "1958", event: "NASA Founded", detail: "National Aeronautics and Space Administration established" },
    { year: "1969", event: "Apollo 11", detail: "Neil Armstrong and Buzz Aldrin land on the Moon" },
    { year: "1977", event: "Voyager Programme", detail: "Voyager 1 & 2 launched on grand tour of outer planets" },
    { year: "1990", event: "Hubble Launched", detail: "Space Telescope transforms astronomy from orbit" },
    { year: "2021", event: "Perseverance + JWST", detail: "Perseverance lands on Mars; JWST launches on Christmas Day" },
    { year: "2025", event: "Artemis II", detail: "First crewed Artemis mission — a lunar flyby" },
    { year: "2026", event: "Artemis III", detail: "First crewed lunar landing since 1972 — at the south pole" },
  ],
  missions: [
    { name: "Artemis II", agency: "NASA", status: "Upcoming", year: "2025", description: "First crewed Artemis mission — 4 astronauts on a lunar flyby" },
    { name: "Artemis III", agency: "NASA", status: "Upcoming", year: "2026", description: "First crewed Moon landing since Apollo 17 — lunar south pole" },
    { name: "Europa Clipper", agency: "NASA", status: "Active", year: "2024", description: "Investigating Jupiter's icy moon Europa for habitability (arrival 2030)" },
    { name: "Perseverance Rover", agency: "NASA", status: "Active", year: "2021", description: "Collecting rock samples for future Mars Sample Return" },
    { name: "Dragonfly", agency: "NASA", status: "Upcoming", year: "2028", description: "Rotorcraft lander exploring Saturn's moon Titan (arrival 2034)" },
  ],
  gallery: [{ src: "/images/space-explorer/NASA.png", caption: "NASA — from Apollo to Artemis, exploring the cosmos" }],
  relatedSlugs: ["launches", "spacecraft", "mars-rover", "iss-tracker"],
  aiPrompts: ["What is the Artemis programme?", "What missions are currently active?", "How far has Voyager travelled?", "When will humans go back to the Moon?"],
};

SPACE_DETAIL["iss-tracker"] = {
  slug: "iss-tracker",
  title: "ISS Tracker",
  subtitle: "Live Position",
  icon: "🛰",
  heroImage: "/images/space-explorer/ISSTracker.png",
  accent: "#38bdf8",
  overview: "The International Space Station is a modular space station in low Earth orbit, jointly operated by NASA, Roscosmos, ESA, JAXA, and CSA. It orbits at approximately 408 km altitude at 27,600 km/h, completing one orbit every 90 minutes. The station has been continuously crewed since November 2, 2000 and serves as a microgravity laboratory for science, medicine, and technology.",
  stats: [
    { label: "Orbital Altitude", value: "~408", unit: "km" },
    { label: "Orbital Speed", value: "27,600", unit: "km/h" },
    { label: "Orbit Period", value: "~90", unit: "minutes" },
    { label: "Station Mass", value: "~420,000", unit: "kg" },
    { label: "Continuously Crewed Since", value: "Nov 2, 2000" },
    { label: "Daily Orbits", value: "~16" },
  ],
  facts: [
    "The ISS is the largest structure ever assembled in space — longer than a football field",
    "Astronauts witness 16 sunrises and sunsets every 24 hours from the ISS",
    "The station has hosted 270+ astronauts from 20 countries",
    "ISS was assembled from 42 separate launches over 13 years",
    "Water is recycled at 93% efficiency, including from urine and sweat",
    "The station is visible to the naked eye from Earth as a fast-moving bright dot",
  ],
  timeline: [
    { year: "1998", event: "First Module Launched", detail: "Zarya control module — first ISS component launched by Russia" },
    { year: "2000", event: "Continuous Habitation", detail: "Expedition 1 crew arrives — ISS becomes permanently crewed" },
    { year: "2011", event: "Assembly Complete", detail: "Final configuration reached after 13 years of construction" },
    { year: "2020", event: "Crew Dragon Arrives", detail: "SpaceX begins commercial crew rotation missions" },
    { year: "2024", event: "Axiom Modules", detail: "Private Axiom Station begins attaching commercial modules" },
    { year: "2030", event: "Planned Deorbit", detail: "ISS planned to deorbit over the Pacific Ocean" },
  ],
  missions: [
    { name: "Expedition 72", agency: "NASA/Roscosmos/ESA/JAXA", status: "Active", year: "2025", description: "Current ISS expedition crew conducting microgravity research" },
    { name: "Crew Dragon Freedom", agency: "SpaceX/NASA", status: "Active", year: "2025", description: "Commercial crew rotation servicing the ISS" },
    { name: "Soyuz MS-27", agency: "Roscosmos", status: "Active", year: "2025", description: "Russian crew segment spacecraft docked at ISS" },
  ],
  gallery: [{ src: "/images/space-explorer/ISSTracker.png", caption: "International Space Station in low Earth orbit" }],
  relatedSlugs: ["earth-live", "earth-observation", "nasa-missions", "satellites"],
  aiPrompts: ["How fast does the ISS orbit?", "Who is on the ISS right now?", "When will the ISS be decommissioned?", "How do astronauts live on the ISS?"],
};

SPACE_DETAIL["earth-live"] = {
  slug: "earth-live",
  title: "Earth Live",
  subtitle: "Blue Marble",
  icon: "🌎",
  heroImage: "/images/space-explorer/Satellite.png",
  accent: "#4ade80",
  overview: "NASA's EPIC (Earth Polychromatic Imaging Camera) aboard the DSCOVR satellite captures full-disc images of Earth from the L1 Lagrange point — 1.5 million km from Earth. EPIC provides a unique perspective of the whole sunlit face of our planet, updated every 1–2 hours. The images are used to study clouds, aerosols, ozone, and vegetation from a global perspective.",
  stats: [
    { label: "DSCOVR Location", value: "L1 Lagrange Point", unit: "(1.5M km)" },
    { label: "EPIC Images Per Day", value: "12–22", unit: "full-disc" },
    { label: "Image Resolution", value: "2048×2048", unit: "pixels" },
    { label: "Wavelength Bands", value: "10", unit: "UV to NIR" },
    { label: "Launch Date", value: "February 11, 2015" },
    { label: "Archive Start", value: "June 13, 2015" },
  ],
  facts: [
    "DSCOVR is positioned at the gravitational equilibrium L1 point — always facing the Sun-lit Earth",
    "EPIC observes Earth in 10 spectral channels from ultraviolet to near-infrared",
    "Each EPIC image shows weather patterns, ice sheets, and vegetation in real time",
    "The Blue Marble photograph (1972) was the inspiration for the DSCOVR mission",
    "DSCOVR also monitors solar wind to provide 15–60 minute space weather warnings",
    "EPIC images are publicly released within 24 hours of acquisition",
  ],
  timeline: [
    { year: "2015", event: "DSCOVR Launches", detail: "SpaceX Falcon 9 delivers DSCOVR to the L1 Lagrange point" },
    { year: "2015", event: "First EPIC Image", detail: "First full Earth disc photograph released to the public" },
    { year: "2016", event: "Daily Coverage", detail: "Continuous daily full-disc Earth imagery established" },
    { year: "2024", event: "Decade of Data", detail: "Nearly 10 years of Earth observation data archived" },
  ],
  missions: [
    { name: "DSCOVR", agency: "NOAA/NASA", status: "Active", year: "2015", description: "Primary host of the EPIC camera at L1, also monitors space weather" },
  ],
  gallery: [{ src: "/images/space-explorer/Satellite.png", caption: "Earth seen by EPIC — full disc from the L1 Lagrange point" }],
  relatedSlugs: ["earth-observation", "iss-tracker", "space-weather"],
  aiPrompts: ["What is NASA EPIC?", "Where is DSCOVR?", "How often does EPIC update?", "What can EPIC see on Earth?"],
};

SPACE_DETAIL["apod"] = {
  slug: "apod",
  title: "Astronomy Picture of the Day",
  subtitle: "NASA APOD",
  icon: "📸",
  heroImage: "/images/space-explorer/NASA.png",
  accent: "#c084fc",
  overview: "NASA's Astronomy Picture of the Day (APOD) has been publishing a new astronomical image every single day since June 16, 1995. Each image is accompanied by a brief explanation written by a professional astronomer. APOD is one of NASA's most popular websites, visited by millions worldwide. Images range from telescope observations to spacecraft photography to citizen astrophotography.",
  stats: [
    { label: "Archive Start", value: "June 16, 1995" },
    { label: "Images Published", value: "10,700+", unit: "and counting" },
    { label: "Daily Visitors", value: "1 Million+", unit: "worldwide" },
    { label: "Languages", value: "21", unit: "mirror sites" },
    { label: "Founded By", value: "Robert Nemiroff & Jerry Bonnell" },
    { label: "Uninterrupted Since", value: "1995", unit: "(30 years)" },
  ],
  facts: [
    "APOD has published a new image every single day since 1995 — never missing a day",
    "It is consistently one of NASA's most-accessed websites",
    "Images are sourced from telescopes, spacecraft, and amateur astrophotographers worldwide",
    "Each explanation is peer-reviewed and written by astronomy professionals",
    "Some APOD images have gone viral before social media — spread via email chains in the 90s",
    "The website uses simple HTML to maximise speed and accessibility worldwide",
  ],
  timeline: [
    { year: "1995", event: "APOD Launches", detail: "First APOD published June 16, 1995 — Valles Marineris panorama" },
    { year: "1999", event: "Millionth Visitor", detail: "APOD celebrates 1 million page visits" },
    { year: "2011", event: "Facebook Launch", detail: "APOD official Facebook page amasses millions of followers" },
    { year: "2022", event: "10,000th Image", detail: "Milestone APOD image published — Cygnus Loop supernova remnant" },
    { year: "2025", event: "30th Anniversary", detail: "Three decades of daily astronomical imagery" },
  ],
  missions: [],
  gallery: [{ src: "/images/space-explorer/NASA.png", caption: "NASA APOD — a different corner of the universe each day" }],
  relatedSlugs: ["mars-rover", "earth-live", "nasa-missions"],
  aiPrompts: ["What is today's APOD image?", "How does NASA select APOD images?", "What has been the most popular APOD?", "How long has APOD been running?"],
  apiSource: "NASA APOD API",
};

SPACE_DETAIL["mars-rover"] = {
  slug: "mars-rover",
  title: "Mars Rover Gallery",
  subtitle: "Perseverance & Curiosity",
  icon: "🎥",
  heroImage: "/images/space-explorer/MarsRover.png",
  accent: "#f87171",
  overview: "NASA's Mars rovers are robotic geologists exploring the Martian surface. Perseverance landed in Jezero Crater in February 2021, collecting rock cores for future sample return. Curiosity has been exploring Gale Crater since 2012. Together they have driven over 100 km, taken millions of photos, and detected organic molecules — strengthening the case that ancient Mars was habitable.",
  stats: [
    { label: "Perseverance Landing", value: "Feb 18, 2021" },
    { label: "Jezero Crater Width", value: "45", unit: "km" },
    { label: "Samples Collected", value: "24+", unit: "rock cores" },
    { label: "Ingenuity Flights", value: "72", unit: "(retired 2024)" },
    { label: "Curiosity Distance", value: "33+", unit: "km driven" },
    { label: "Mars Day (Sol)", value: "24h 39m" },
  ],
  facts: [
    "Perseverance produced the first oxygen from Martian CO₂ using the MOXIE experiment",
    "The Ingenuity helicopter completed 72 flights — the first powered flight on another planet — before being retired in January 2024",
    "Curiosity discovered organic molecules and seasonal methane variations in Gale Crater",
    "Perseverance's rock cores will be collected by a future Mars Sample Return mission (2030s)",
    "Rovers communicate with Earth via the Deep Space Network with a ~20-minute signal delay",
    "Jezero Crater is an ancient lake bed — perfect for searching for signs of past microbial life",
  ],
  timeline: [
    { year: "2004", event: "Spirit & Opportunity Land", detail: "Twin rovers begin surface operations; Opportunity lasts 15 years" },
    { year: "2012", event: "Curiosity Lands", detail: "Most sophisticated rover at the time lands in Gale Crater" },
    { year: "2021", event: "Perseverance Lands", detail: "Jezero Crater landing; Ingenuity helicopter deploys" },
    { year: "2021", event: "First Mars Flight", detail: "Ingenuity makes first powered flight on another world" },
    { year: "2023", event: "MOXIE Completes", detail: "Perseverance produces oxygen from CO₂ — confirms Mars ISRU is possible" },
    { year: "2024", event: "Ingenuity Retired", detail: "Helicopter damaged on Flight 72; Perseverance continues solo" },
  ],
  missions: [
    { name: "Perseverance", agency: "NASA", status: "Active", year: "2021", description: "Collecting samples in Jezero Crater for future return to Earth" },
    { name: "Curiosity", agency: "NASA", status: "Active", year: "2012", description: "Exploring Gale Crater; studying climate history and habitability" },
    { name: "Mars Sample Return", agency: "NASA/ESA", status: "Upcoming", year: "2030s", description: "Will retrieve Perseverance's rock cores and bring them to Earth" },
  ],
  gallery: [{ src: "/images/space-explorer/MarsRover.png", caption: "NASA Perseverance rover — exploring Jezero Crater" }],
  relatedSlugs: ["mars", "nasa-missions", "neo", "spacecraft"],
  aiPrompts: ["What has Perseverance found?", "What is Jezero Crater?", "How many Mars rovers are active?", "When will Mars samples return to Earth?"],
  apiSource: "NASA Mars Rover Photos API",
};

SPACE_DETAIL["neo"] = {
  slug: "neo",
  title: "Near Earth Objects",
  subtitle: "Planetary Defense",
  icon: "☄",
  heroImage: "/images/space-explorer/NearEarthObject.png",
  accent: "#fb7185",
  overview: "Near-Earth Objects (NEOs) are asteroids and comets whose orbits bring them within 1.3 AU of the Sun — and thus potentially close to Earth. NASA's Center for Near Earth Object Studies (CNEOS) tracks all known NEOs. Of the 33,000+ known NEAs, around 2,300 are classified as Potentially Hazardous Asteroids (PHAs). The 2022 DART mission proved we can deflect an asteroid — humanity's first planetary defence test.",
  stats: [
    { label: "Known Near-Earth Asteroids", value: "33,000+", unit: "as of 2025" },
    { label: "Potentially Hazardous", value: "~2,300", unit: "PHAs" },
    { label: "DART Deflection", value: "33 min", unit: "orbital period change" },
    { label: "Apophis Close Approach", value: "April 13, 2029" },
    { label: "Apophis Miss Distance", value: "~32,000", unit: "km" },
    { label: "Average Discovery Rate", value: "~3,000", unit: "per year" },
  ],
  facts: [
    "Apophis will pass within 32,000 km of Earth on April 13, 2029 — closer than geostationary satellites",
    "DART changed Dimorphos's orbital period by 33 minutes — far more than the minimum threshold",
    "A 1 km asteroid impact would cause global climate disruption; none known on collision course",
    "OSIRIS-REx (now OSIRIS-APEX) is en route to Apophis, arriving just before the 2029 flyby",
    "The Chelyabinsk meteor in 2013 (17m diameter) injured 1,500 people without warning",
    "NASA's Planetary Defense Coordination Office monitors all known PHAs in real time",
  ],
  timeline: [
    { year: "1998", event: "Spaceguard Programme", detail: "Congress directs NASA to find 90% of NEAs larger than 1 km" },
    { year: "2005", event: "Deep Impact", detail: "Comet Tempel 1 impacted to study interior composition" },
    { year: "2013", event: "Chelyabinsk Event", detail: "Undetected 17m meteor airburst injures 1,500 in Russia" },
    { year: "2022", event: "DART Success", detail: "NASA's DART spacecraft deflects asteroid Dimorphos" },
    { year: "2024", event: "Hera Launch", detail: "ESA's Hera mission launched to study DART's Dimorphos impact" },
    { year: "2029", event: "Apophis Flyby", detail: "Apophis passes 32,000 km from Earth — closest known PHA approach" },
  ],
  missions: [
    { name: "OSIRIS-APEX", agency: "NASA", status: "Active", year: "2023", description: "Formerly OSIRIS-REx, now heading to intercept Apophis before its 2029 flyby" },
    { name: "Hera", agency: "ESA", status: "Active", year: "2024", description: "Studying the DART impact crater on Dimorphos (arrives 2026)" },
    { name: "NEO Surveyor", agency: "NASA", status: "Upcoming", year: "2027", description: "Space-based infrared telescope to find and characterise PHAs" },
  ],
  gallery: [{ src: "/images/space-explorer/NearEarthObject.png", caption: "Asteroid Dimorphos — target of the DART planetary defence mission" }],
  relatedSlugs: ["asteroids", "comets", "nasa-missions"],
  aiPrompts: ["Will Apophis hit Earth?", "What was the DART mission?", "How many asteroids could hit Earth?", "What is a potentially hazardous asteroid?"],
  apiSource: "NASA NeoWs API",
};

SPACE_DETAIL["space-weather"] = {
  slug: "space-weather",
  title: "Space Weather",
  subtitle: "Solar Dynamics",
  icon: "☀",
  heroImage: "/images/space-explorer/SpaceWeather.png",
  accent: "#fb923c",
  overview: "Space weather refers to conditions in space driven by the Sun's activity — solar flares, coronal mass ejections (CMEs), and solar wind. These phenomena can disrupt satellite operations, power grids, GPS signals, and radio communications on Earth. The NOAA Space Weather Prediction Center issues real-time alerts. The most powerful recorded geomagnetic storm — the Carrington Event of 1859 — would cause trillions in damage if it happened today.",
  stats: [
    { label: "Solar Cycle 25 Peak", value: "2025", unit: "(stronger than expected)" },
    { label: "X-Class Flare Max Power", value: "~10²⁵", unit: "joules" },
    { label: "CME Speed", value: "250–3,000", unit: "km/s" },
    { label: "Carrington Event", value: "1859", unit: "(strongest ever)" },
    { label: "Solar Wind Speed", value: "400–800", unit: "km/s (avg)" },
    { label: "DSCOVR Warning Time", value: "15–60", unit: "minutes advance" },
  ],
  facts: [
    "The 1859 Carrington Event caused telegraph systems worldwide to catch fire — a repeat would be catastrophic",
    "Solar Cycle 25 has been significantly stronger than predicted — more flares and CMEs than forecast",
    "CMEs can take 1–3 days to reach Earth after leaving the Sun",
    "GPS accuracy degrades during strong geomagnetic storms due to ionospheric disturbances",
    "The aurora borealis seen at unusually low latitudes in May 2024 was caused by an X9 solar flare",
    "Airline flights over polar routes are rerouted during solar radiation storms",
  ],
  timeline: [
    { year: "1859", event: "Carrington Event", detail: "Largest recorded solar storm — telegraph lines caught fire worldwide" },
    { year: "1989", event: "Quebec Blackout", detail: "Geomagnetic storm knocks out power to 6 million people for 9 hours" },
    { year: "2003", event: "Halloween Storms", detail: "X28-class flares — largest ever recorded — disrupt satellites and GPS" },
    { year: "2015", event: "DSCOVR Launch", detail: "Real-time solar wind monitoring from L1 begins" },
    { year: "2024", event: "X9 Flare Event", detail: "Strong X-class flares produce auroras visible at 30° latitude" },
    { year: "2025", event: "Solar Maximum", detail: "Solar Cycle 25 reaches peak activity — elevated flare probability" },
  ],
  missions: [
    { name: "DSCOVR", agency: "NOAA/NASA", status: "Active", year: "2015", description: "Solar wind monitoring at L1 — primary space weather warning system" },
    { name: "Parker Solar Probe", agency: "NASA", status: "Active", year: "2018", description: "Closest solar approach ever — studying CME origins in the corona" },
    { name: "Solar Orbiter", agency: "ESA/NASA", status: "Active", year: "2020", description: "High-latitude imaging of solar poles and activity regions" },
    { name: "GOES-18", agency: "NOAA", status: "Active", year: "2022", description: "Geosynchronous satellite monitoring X-ray flares in real time" },
  ],
  gallery: [{ src: "/images/space-explorer/SpaceWeather.png", caption: "A powerful solar flare erupting from the Sun's surface" }],
  relatedSlugs: ["earth-observation", "earth-live", "satellites", "astronomy-research"],
  aiPrompts: ["What is a solar flare?", "What was the Carrington Event?", "How does space weather affect Earth?", "What are the Northern Lights?", "When is the next solar maximum?"],
  apiSource: "NASA DONKI API",
};

// Inject rich data for key slugs
Object.assign(SPACE_DETAIL["spacecraft"], {
  overview: "From the first artificial satellite Sputnik 1 to the distant Voyager probes sailing in interstellar space, spacecraft have become humanity's eyes and hands across the cosmos. Modern spacecraft like the James Webb Space Telescope peer back to the first light after the Big Bang.",
  stats: [
    { label: "Voyager 1 Distance", value: "23.5 Billion", unit: "km" },
    { label: "JWST Mirror", value: "6.5", unit: "m diameter" },
    { label: "Hubble Observations", value: "1.5 Million+" },
    { label: "Active Missions", value: "60+", unit: "NASA" },
  ],
  facts: [
    "Voyager 1 is the most distant human-made object ever",
    "The ISS is as large as an American football field",
    "James Webb can see galaxies 13.6 billion light-years away",
    "The Parker Solar Probe is the fastest human-made object at 635,000 km/h",
    "Cassini collected data for 13 years around Saturn",
    "New Horizons gave us our first clear look at Pluto in 2015",
  ],
  timeline: [
    { year: "1957", event: "Sputnik 1", detail: "First artificial satellite, USSR" },
    { year: "1969", event: "Apollo 11", detail: "First crewed lunar landing" },
    { year: "1977", event: "Voyager Launch", detail: "Both Voyagers launch on grand tour" },
    { year: "1990", event: "Hubble Launch", detail: "Space Telescope transforms astronomy" },
    { year: "2021", event: "James Webb Launch", detail: "Next-generation space telescope deployed" },
    { year: "2024", event: "Europa Clipper", detail: "Mission to Jupiter's moon Europa" },
  ],
  missions: [
    { name: "James Webb Space Telescope", agency: "NASA/ESA/CSA", status: "Active", year: "2021", description: "Infrared telescope at L2, observing early universe" },
    { name: "Hubble Space Telescope", agency: "NASA/ESA", status: "Active", year: "1990", description: "34+ years of transformative astronomical observations" },
    { name: "Voyager 1", agency: "NASA", status: "Active", year: "1977", description: "In interstellar space, 23+ billion km from Earth" },
    { name: "Parker Solar Probe", agency: "NASA", status: "Active", year: "2018", description: "Closest spacecraft ever to the Sun" },
    { name: "Cassini", agency: "NASA/ESA", status: "Completed", year: "1997", description: "Studied Saturn system for 13 years" },
    { name: "New Horizons", agency: "NASA", status: "Active", year: "2006", description: "Explored Pluto and Kuiper Belt" },
  ],
  aiPrompts: [
    "How far away is Voyager 1?",
    "What can James Webb see that Hubble can't?",
    "Which spacecraft has travelled farthest?",
    "What will the Europa Clipper find?",
  ],
});

Object.assign(SPACE_DETAIL["apod"], {
  overview: "NASA's Astronomy Picture of the Day (APOD) has been publishing a new astronomical image every single day since June 16, 1995. Each image is accompanied by a brief explanation written by a professional astronomer. APOD is one of NASA's most popular websites, visited by millions worldwide.",
  stats: [
    { label: "Archive Start", value: "June 16, 1995" },
    { label: "Images Published", value: "10,000+" },
    { label: "Daily Visitors", value: "1 Million+" },
    { label: "Languages", value: "21" },
  ],
  facts: [
    "APOD has been published every day since 1995 without interruption",
    "It is one of NASA's most-accessed websites",
    "Images are selected from telescopes, spacecraft, and citizen astronomers",
    "Each image is explained by professional astronomers",
    "The archive contains over 10,000 unique images",
  ],
  aiPrompts: [
    "What is today's APOD image?",
    "How does NASA select APOD images?",
    "What has been the most popular APOD?",
    "Can I submit a photo to APOD?",
  ],
});

Object.assign(SPACE_DETAIL["black-holes"], {
  overview: "Black holes are regions of spacetime where gravity is so intense that nothing — not even electromagnetic radiation — can escape once past the event horizon. They form when massive stars collapse at the end of their lives, or through other extreme processes. In 2019, the Event Horizon Telescope produced the first image of a black hole's shadow: M87*, a supermassive black hole 6.5 billion times the mass of our Sun.",
  stats: [
    { label: "M87* Mass", value: "6.5 Billion", unit: "× Sun" },
    { label: "Sagittarius A* Mass", value: "4 Million", unit: "× Sun" },
    { label: "Event Horizon Image", value: "April 10, 2019" },
    { label: "Closest BH to Earth", value: "~1,500", unit: "light-years" },
  ],
  facts: [
    "Sagittarius A* is the supermassive black hole at the Milky Way's center",
    "Black holes don't suck — they only affect things that come too close",
    "Time passes slower near a black hole (gravitational time dilation)",
    "The first black hole ever photographed is M87* in 2019",
    "Stephen Hawking proposed that black holes slowly evaporate via Hawking radiation",
    "Supermassive black holes exist at the center of nearly all large galaxies",
  ],
  timeline: [
    { year: "1916", event: "Schwarzschild Solution", detail: "Karl Schwarzschild derives first black hole solution" },
    { year: "1967", event: "Term 'Black Hole' Coined", detail: "John Wheeler popularizes the term" },
    { year: "1974", event: "Hawking Radiation", detail: "Hawking predicts black holes slowly evaporate" },
    { year: "2015", event: "Gravitational Waves", detail: "LIGO detects waves from black hole merger" },
    { year: "2019", event: "First Image", detail: "EHT photographs M87* event horizon shadow" },
    { year: "2022", event: "Milky Way BH Imaged", detail: "EHT images Sagittarius A* for the first time" },
  ],
  aiPrompts: [
    "What happens if you fall into a black hole?",
    "How are black holes detected?",
    "What is Hawking radiation?",
    "Is there a black hole in the Milky Way?",
  ],
});

SPACE_DETAIL["launches"] = {
  slug: "launches",
  title: "Launch Tracker",
  subtitle: "Global Rocket Launches",
  icon: "🛸",
  heroImage: "/images/space-explorer/SpaceCraft.png",
  accent: "#34d399",
  overview:
    "The Launch Tracker provides real-time data on upcoming and recent rocket launches worldwide, aggregated from the Launch Library 2 open API. From SpaceX Falcon 9 missions to ISRO PSLV launches and ESA Ariane flights, every major orbital and suborbital launch is tracked here with countdown timers, mission details, and launch pad information.",
  stats: [
    { label: "Launches in 2024", value: "220+", unit: "Global" },
    { label: "Space Agencies", value: "15+", unit: "Active" },
    { label: "SpaceX Flights", value: "96+", unit: "in 2024" },
    { label: "Success Rate", value: "98.5%", unit: "(2024 avg)" },
    { label: "Orbital Missions", value: "180+", unit: "in 2024" },
    { label: "Crewed Missions", value: "8", unit: "in 2024" },
  ],
  facts: [
    "SpaceX became the first private company to launch humans to orbit in 2020",
    "Falcon 9 has the highest launch cadence of any rocket in history",
    "Starship is the largest rocket ever built at 120m tall",
    "India's PSLV has a 95%+ success rate over 60+ launches",
    "Reusable rockets have reduced launch costs by up to 90%",
  ],
  timeline: [
    { year: "1957", event: "Sputnik 1", detail: "World's first artificial satellite launched by the Soviet Union" },
    { year: "1969", event: "Apollo 11", detail: "First humans land on the Moon" },
    { year: "2015", event: "Falcon 9 Landing", detail: "SpaceX lands first orbital rocket booster" },
    { year: "2020", event: "Crew Dragon", detail: "SpaceX launches first private crewed mission to ISS" },
    { year: "2023", event: "Starship IFT-1", detail: "First integrated flight test of Starship/Super Heavy" },
  ],
  missions: [
    { name: "Starship IFT-6", agency: "SpaceX", status: "Upcoming", year: "2025", description: "Sixth integrated flight test targeting full mission profile" },
    { name: "Artemis II", agency: "NASA", status: "Upcoming", year: "2025", description: "First crewed Artemis mission — lunar flyby" },
    { name: "NISAR", agency: "NASA/ISRO", status: "Upcoming", year: "2025", description: "Joint Earth observation radar satellite" },
  ],
  gallery: [
    { src: "/images/space-explorer/SpaceCraft.png", caption: "Rocket launches: humanity's reach into space" },
  ],
  relatedSlugs: ["spacex", "nasa-missions", "iss-tracker"],
  aiPrompts: [
    "What upcoming launches should I watch?",
    "Tell me about Starship",
    "What is the most reliable rocket?",
    "How many rockets launched this year?",
  ],
  apiSource: "Launch Library 2",
};

SPACE_DETAIL["spacex"] = {
  slug: "spacex",
  title: "SpaceX",
  subtitle: "Commercial Space Leader",
  icon: "🚀",
  heroImage: "/images/space-explorer/SpaceCraft.png",
  accent: "#60a5fa",
  overview:
    "SpaceX, founded by Elon Musk in 2002, has fundamentally transformed commercial spaceflight. With reusable rockets, the Falcon 9 has become the world's most flown orbital launcher. Dragon has delivered crew and cargo to the ISS, while Starship promises fully reusable transport to the Moon, Mars, and beyond. SpaceX's cadence now exceeds all other launch providers combined.",
  stats: [
    { label: "Falcon 9 Flights", value: "350+", unit: "total" },
    { label: "Booster Reuses", value: "20+", unit: "max per booster" },
    { label: "Starlink Sats", value: "6,000+", unit: "in orbit" },
    { label: "Crewed Missions", value: "15+", unit: "to ISS" },
    { label: "Success Rate", value: "98.7%", unit: "Falcon 9" },
    { label: "Starship Height", value: "120", unit: "meters" },
  ],
  facts: [
    "Falcon 9 was the first orbital-class rocket to successfully land and refly a booster",
    "Dragon is the first commercial spacecraft certified for human spaceflight by NASA",
    "Starship produces 16.7 million pounds of thrust — more than any rocket in history",
    "SpaceX operates the world's largest private satellite constellation (Starlink)",
    "A single Falcon 9 booster has been flown 22 times",
  ],
  timeline: [
    { year: "2002", event: "SpaceX Founded", detail: "Elon Musk founds Space Exploration Technologies Corp." },
    { year: "2008", event: "Falcon 1 Orbit", detail: "First privately developed liquid-fueled rocket to reach orbit" },
    { year: "2012", event: "Dragon CRS-1", detail: "First private spacecraft to berth with the ISS" },
    { year: "2015", event: "Booster Landing", detail: "Falcon 9 first stage lands at Cape Canaveral" },
    { year: "2020", event: "Crew Dragon Demo-2", detail: "First private crewed spaceflight to the ISS" },
    { year: "2023", event: "Starship Test Flights", detail: "IFT-1 through IFT-4 progressively successful" },
  ],
  missions: [
    { name: "Crew Dragon Endurance", agency: "SpaceX/NASA", status: "Active", year: "2024", description: "Commercial Crew rotation mission to ISS" },
    { name: "Starlink v2 Mini", agency: "SpaceX", status: "Active", year: "2024", description: "Next-gen Starlink satellites with 4× capacity" },
    { name: "Polaris Dawn", agency: "SpaceX", status: "Completed", year: "2024", description: "First private spacewalk in history" },
  ],
  gallery: [
    { src: "/images/space-explorer/SpaceCraft.png", caption: "SpaceX Dragon capsule on approach to ISS" },
  ],
  relatedSlugs: ["launches", "nasa-missions", "spacecraft"],
  aiPrompts: [
    "Tell me about Starship",
    "How does Falcon 9 land?",
    "What is Dragon spacecraft?",
    "How many Starlink satellites are in orbit?",
    "Compare SpaceX to NASA",
  ],
};

SPACE_DETAIL["exoplanets"] = {
  slug: "exoplanets",
  title: "Exoplanets",
  subtitle: "Worlds Beyond Our Sun",
  icon: "🪐",
  heroImage: "/images/space-explorer/ExoPlanet.png",
  accent: "#a78bfa",
  overview:
    "An exoplanet is any planet that orbits a star other than our Sun. As of 2024, NASA's Exoplanet Archive contains over 5,700 confirmed discoveries. The James Webb Space Telescope is now characterizing their atmospheres, searching for biosignatures — chemical signs of life. From ultra-hot Jupiters to potentially habitable super-Earths, the diversity of worlds is staggering.",
  stats: [
    { label: "Confirmed Exoplanets", value: "5,700+", unit: "as of 2024" },
    { label: "Habitable Zone Candidates", value: "60+", unit: "Earth-like" },
    { label: "Detection Methods", value: "7+", unit: "techniques" },
    { label: "TRAPPIST-1 Planets", value: "7", unit: "(3 in HZ)" },
    { label: "Nearest Exoplanet", value: "4.2", unit: "light years" },
    { label: "JWST Atmospheres", value: "25+", unit: "characterized" },
  ],
  facts: [
    "Proxima Centauri b is the closest known exoplanet at just 4.2 light years away",
    "TRAPPIST-1 system has 3 planets in the habitable zone around a single star",
    "K2-18b may have a water-rich atmosphere detectable by JWST",
    "Some exoplanets orbit their stars in less than 1 Earth day",
    "The first confirmed exoplanet discovery was in 1992, orbiting a pulsar",
    "NASA's Kepler mission discovered over 2,600 exoplanets alone",
  ],
  timeline: [
    { year: "1992", event: "First Exoplanet", detail: "Wolszczan & Frail discover planets orbiting pulsar PSR 1257+12" },
    { year: "1995", event: "51 Pegasi b", detail: "First exoplanet found around a Sun-like star" },
    { year: "2009", event: "Kepler Launched", detail: "NASA's planet-hunting telescope begins operations" },
    { year: "2017", event: "TRAPPIST-1", detail: "Seven Earth-sized planets discovered around nearby dwarf star" },
    { year: "2021", event: "JWST Launch", detail: "James Webb Space Telescope begins atmospheric characterization" },
    { year: "2023", event: "K2-18b Atmosphere", detail: "JWST detects possible dimethyl sulfide — potential biosignature" },
  ],
  missions: [
    { name: "James Webb Space Telescope", agency: "NASA/ESA/CSA", status: "Active", year: "2021", description: "Characterizing exoplanet atmospheres in unprecedented detail" },
    { name: "TESS", agency: "NASA", status: "Active", year: "2018", description: "Transiting Exoplanet Survey Satellite — all-sky planet finder" },
    { name: "CHEOPS", agency: "ESA", status: "Active", year: "2019", description: "Characterising Exoplanet Satellite — precise radius measurements" },
    { name: "PLATO", agency: "ESA", status: "Upcoming", year: "2026", description: "PLAnetary Transits and Oscillations — Earth-twin search" },
  ],
  gallery: [
    { src: "/images/space-explorer/ExoPlanet.png", caption: "Artist's conception of a habitable exoplanet" },
  ],
  relatedSlugs: ["astronomy-research", "stars", "nasa-missions"],
  aiPrompts: [
    "Which exoplanet is most like Earth?",
    "How do we detect exoplanets?",
    "Tell me about TRAPPIST-1",
    "Could life exist on K2-18b?",
    "What is the habitable zone?",
  ],
  apiSource: "NASA Exoplanet Archive",
};

export function getCategoryBySlug(slug: string): SpaceCategory | undefined {
  return SPACE_CATEGORIES.find((c) => c.slug === slug);
}

export function getDetailBySlug(slug: string): SpaceDetailData | undefined {
  return SPACE_DETAIL[slug];
}
