export interface SpaceCategory {
  slug: string;
  icon: string;
  title: string;
  subtitle: string;
  description: string;
  accent: string;
  glow: string;
  status: string;
  statusColor: string;
  image: string;
  tags: string[];
}

export interface SpaceDetailData {
  slug: string;
  title: string;
  subtitle: string;
  icon: string;
  heroImage: string;
  accent: string;
  overview: string;
  stats: { label: string; value: string; unit?: string }[];
  facts: string[];
  timeline: { year: string; event: string; detail: string }[];
  missions: { name: string; agency: string; status: string; year: string; description: string }[];
  gallery: { src: string; caption: string }[];
  relatedSlugs: string[];
  aiPrompts: string[];
  apiSource?: string;
}

export const SPACE_CATEGORIES: SpaceCategory[] = [
  {
    slug: "solar-system",
    icon: "🪐",
    title: "Solar System",
    subtitle: "Our Cosmic Home",
    description: "Eight planets, hundreds of moons, millions of asteroids orbiting our star.",
    accent: "#f59e0b",
    glow: "rgba(245,158,11,0.35)",
    status: "8 Planets",
    statusColor: "#f59e0b",
    image: "/images/space-explorer/SolarSystemSpaceExplorer.png",
    tags: ["Planets", "Moons", "Orbits"],
  },
  {
    slug: "dwarf-planets",
    icon: "🌠",
    title: "Dwarf Planets",
    subtitle: "Beyond Neptune",
    description: "Pluto, Eris, Makemake and the fascinating worlds of the outer solar system.",
    accent: "#a78bfa",
    glow: "rgba(167,139,250,0.35)",
    status: "5 Classified",
    statusColor: "#a78bfa",
    image: "/images/space-explorer/DwarfPlanets.png",
    tags: ["Pluto", "Kuiper Belt", "Trans-Neptunian"],
  },
  {
    slug: "asteroids",
    icon: "☄",
    title: "Asteroids",
    subtitle: "Rocky Remnants",
    description: "Rocky leftovers from solar system formation, spanning from dust to hundreds of km wide.",
    accent: "#94a3b8",
    glow: "rgba(148,163,184,0.35)",
    status: "1M+ Known",
    statusColor: "#94a3b8",
    image: "/images/space-explorer/Asteroid.png",
    tags: ["NEO", "Asteroid Belt", "Impact"],
  },
  {
    slug: "comets",
    icon: "☄",
    title: "Comets",
    subtitle: "Icy Wanderers",
    description: "Icy bodies from the outer solar system that display glowing tails as they approach the Sun.",
    accent: "#67e8f9",
    glow: "rgba(103,232,249,0.35)",
    status: "Active Tracking",
    statusColor: "#67e8f9",
    image: "/images/space-explorer/Comet.png",
    tags: ["Comet", "Halley", "Oort Cloud"],
  },
  {
    slug: "satellites",
    icon: "🛰",
    title: "Satellites",
    subtitle: "Orbital Observers",
    description: "Thousands of artificial satellites monitor Earth, relay communications, and explore space.",
    accent: "#34d399",
    glow: "rgba(52,211,153,0.35)",
    status: "~8,800 Active",
    statusColor: "#34d399",
    image: "/images/space-explorer/Satellite.png",
    tags: ["LEO", "GPS", "Communication"],
  },
  {
    slug: "spacecraft",
    icon: "🚀",
    title: "Spacecraft",
    subtitle: "Humanity's Reach",
    description: "Voyager, Hubble, JWST — the machines that extended our senses across the cosmos.",
    accent: "#60a5fa",
    glow: "rgba(96,165,250,0.35)",
    status: "Active Missions",
    statusColor: "#60a5fa",
    image: "/images/space-explorer/SpaceCraft.png",
    tags: ["Voyager", "JWST", "Probes"],
  },
  {
    slug: "earth-observation",
    icon: "🌍",
    title: "Earth Observation",
    subtitle: "Our Living Planet",
    description: "Satellite imagery, climate monitoring, and real-time data of our changing world.",
    accent: "#22c55e",
    glow: "rgba(34,197,94,0.35)",
    status: "Live Data",
    statusColor: "#22c55e",
    image: "/images/space-explorer/Satellite.png",
    tags: ["Climate", "Landsat", "EPIC"],
  },
  {
    slug: "space-weather",
    icon: "☀",
    title: "Space Weather",
    subtitle: "Solar Dynamics",
    description: "Solar flares, coronal mass ejections, and geomagnetic storms from our active Sun.",
    accent: "#fb923c",
    glow: "rgba(251,146,60,0.35)",
    status: "Real-time",
    statusColor: "#fb923c",
    image: "/images/space-explorer/SpaceWeather.png",
    tags: ["Solar Flares", "CME", "Aurora"],
  },
  {
    slug: "exoplanets",
    icon: "🌠",
    title: "Exoplanets",
    subtitle: "Worlds Beyond",
    description: "Over 5,700 confirmed worlds orbiting other stars — some potentially habitable.",
    accent: "#e879f9",
    glow: "rgba(232,121,249,0.35)",
    status: "5,700+ Confirmed",
    statusColor: "#e879f9",
    image: "/images/space-explorer/ExoPlanet.png",
    tags: ["Kepler", "TESS", "Habitable Zone"],
  },
  {
    slug: "stars",
    icon: "⭐",
    title: "Stars",
    subtitle: "Cosmic Furnaces",
    description: "From red dwarfs to blue supergiants — the nuclear furnaces powering the universe.",
    accent: "#fde68a",
    glow: "rgba(253,230,138,0.35)",
    status: "200B+ in Milky Way",
    statusColor: "#fde68a",
    image: "/images/space-explorer/Stars.png",
    tags: ["Main Sequence", "Supernovae", "Neutron Stars"],
  },
  {
    slug: "galaxies",
    icon: "🌌",
    title: "Galaxies",
    subtitle: "Island Universes",
    description: "Trillions of galaxies populate the observable universe, each containing billions of stars.",
    accent: "#818cf8",
    glow: "rgba(129,140,248,0.35)",
    status: "2T+ Estimated",
    statusColor: "#818cf8",
    image: "/images/space-explorer/Galaxies.png",
    tags: ["Milky Way", "Andromeda", "Clusters"],
  },
  {
    slug: "nebulae",
    icon: "🌌",
    title: "Nebulae",
    subtitle: "Stellar Nurseries",
    description: "Vast clouds of gas and dust — the birthplace and graveyard of stars.",
    accent: "#f472b6",
    glow: "rgba(244,114,182,0.35)",
    status: "Thousands Mapped",
    statusColor: "#f472b6",
    image: "/images/space-explorer/Nebulae.png",
    tags: ["Orion", "Pillars of Creation", "Planetary"],
  },
  {
    slug: "black-holes",
    icon: "⚫",
    title: "Black Holes",
    subtitle: "Gravity's Extreme",
    description: "Regions of spacetime where gravity is so intense that nothing — not even light — escapes.",
    accent: "#6366f1",
    glow: "rgba(99,102,241,0.35)",
    status: "M87* Imaged 2019",
    statusColor: "#6366f1",
    image: "/images/space-explorer/BlackHole.png",
    tags: ["Singularity", "Event Horizon", "Hawking"],
  },
  {
    slug: "astronomy-research",
    icon: "🧬",
    title: "Astronomy Research",
    subtitle: "Frontier Science",
    description: "Dark matter, gravitational waves, and the cosmic microwave background — the universe's deepest mysteries.",
    accent: "#2dd4bf",
    glow: "rgba(45,212,191,0.35)",
    status: "Active Research",
    statusColor: "#2dd4bf",
    image: "/images/space-explorer/Stars.png",
    tags: ["Dark Matter", "LIGO", "CMB"],
  },
  {
    slug: "nasa-missions",
    icon: "🚀",
    title: "NASA Missions",
    subtitle: "Exploration Legacy",
    description: "Apollo to Artemis — decades of missions defining humanity's presence in space.",
    accent: "#3b82f6",
    glow: "rgba(59,130,246,0.35)",
    status: "Active Programs",
    statusColor: "#3b82f6",
    image: "/images/space-explorer/NASA.png",
    tags: ["Apollo", "Artemis", "Mars 2020"],
  },
  {
    slug: "iss-tracker",
    icon: "🛰",
    title: "ISS Tracker",
    subtitle: "Live Position",
    description: "Track the International Space Station live as it orbits Earth every 90 minutes.",
    accent: "#38bdf8",
    glow: "rgba(56,189,248,0.35)",
    status: "Orbiting Now",
    statusColor: "#38bdf8",
    image: "/images/space-explorer/ISSTracker.png",
    tags: ["Live", "ISS", "Orbit"],
  },
  {
    slug: "earth-live",
    icon: "🌎",
    title: "Earth Live",
    subtitle: "Blue Marble",
    description: "Real-time NASA EPIC imagery of Earth's full disc from the DSCOVR satellite.",
    accent: "#4ade80",
    glow: "rgba(74,222,128,0.35)",
    status: "NASA EPIC",
    statusColor: "#4ade80",
    image: "/images/space-explorer/Satellite.png",
    tags: ["EPIC", "DSCOVR", "Real-time"],
  },
  {
    slug: "apod",
    icon: "📸",
    title: "Astronomy Picture of the Day",
    subtitle: "NASA APOD",
    description: "Each day a different image or photograph of our universe, explained by astronomers.",
    accent: "#c084fc",
    glow: "rgba(192,132,252,0.35)",
    status: "Daily Updated",
    statusColor: "#c084fc",
    image: "/images/space-explorer/NASA.png",
    tags: ["APOD", "Photography", "NASA"],
  },
  {
    slug: "mars-rover",
    icon: "🎥",
    title: "Mars Rover Gallery",
    subtitle: "Perseverance & Curiosity",
    description: "Latest photos beamed back from NASA's rovers exploring the Martian surface.",
    accent: "#f87171",
    glow: "rgba(248,113,113,0.35)",
    status: "Live Photos",
    statusColor: "#f87171",
    image: "/images/space-explorer/MarsRover.png",
    tags: ["Perseverance", "Curiosity", "Jezero"],
  },
  {
    slug: "neo",
    icon: "☄",
    title: "Near Earth Objects",
    subtitle: "Planetary Defense",
    description: "Asteroids and comets whose orbits bring them close to Earth — tracked daily by NASA.",
    accent: "#fb7185",
    glow: "rgba(251,113,133,0.35)",
    status: "Live NeoWs",
    statusColor: "#fb7185",
    image: "/images/space-explorer/NearEarthObject.png",
    tags: ["NEO", "Hazardous", "DART"],
  },
  {
    slug: "launches",
    icon: "🛸",
    title: "Launch Tracker",
    subtitle: "Global Rocket Launches",
    description: "Upcoming and recent rocket launches from every space agency worldwide, powered by Launch Library 2.",
    accent: "#34d399",
    glow: "rgba(52,211,153,0.35)",
    status: "Live Launches",
    statusColor: "#34d399",
    image: "/images/space-explorer/SpaceCraft.png",
    tags: ["Launches", "SpaceX", "ISRO", "Live"],
  },
  {
    slug: "spacex",
    icon: "🚀",
    title: "SpaceX",
    subtitle: "Commercial Space Leader",
    description: "Falcon 9, Starship, Dragon missions — the company that redefined commercial spaceflight.",
    accent: "#60a5fa",
    glow: "rgba(96,165,250,0.35)",
    status: "Active Missions",
    statusColor: "#60a5fa",
    image: "/images/space-explorer/SpaceCraft.png",
    tags: ["SpaceX", "Falcon 9", "Starship", "Missions"],
  },
  {
    slug: "exoplanets",
    icon: "🪐",
    title: "Exoplanets",
    subtitle: "Worlds Beyond Our Sun",
    description: "Over 5,700 confirmed exoplanets discovered — explore potentially habitable worlds from NASA's archive.",
    accent: "#a78bfa",
    glow: "rgba(167,139,250,0.35)",
    status: "5700+ Confirmed",
    statusColor: "#a78bfa",
    image: "/images/space-explorer/ExoPlanet.png",
    tags: ["Exoplanets", "Habitable Zone", "NASA", "TRAPPIST"],
  },
];

export const SPACE_DETAIL: Record<string, SpaceDetailData> = {
  "solar-system": {
    slug: "solar-system",
    title: "Solar System",
    subtitle: "Our Cosmic Home",
    icon: "🪐",
    heroImage: "/images/planets/saturn.png",
    accent: "#f59e0b",
    overview:
      "Our Solar System formed approximately 4.6 billion years ago from a giant molecular cloud. The Sun contains 99.86% of all mass, while eight planets, 290+ moons, millions of asteroids, and billions of comets orbit within its gravitational influence. From the scorched rocky worlds of the inner system to the icy giants beyond the asteroid belt, each body tells a unique story of planetary formation.",
    stats: [
      { label: "Age", value: "4.6 Billion", unit: "Years" },
      { label: "Planets", value: "8" },
      { label: "Known Moons", value: "290+" },
      { label: "Diameter", value: "287.46 Billion", unit: "km" },
      { label: "Distance to Edge", value: "2 Light Years" },
      { label: "Speed Through Galaxy", value: "828,000", unit: "km/h" },
    ],
    facts: [
      "The Sun contains 99.86% of all the mass in the Solar System",
      "Jupiter is more than twice as massive as all other planets combined",
      "A day on Venus is longer than a year on Venus",
      "Saturn's rings are only about 10 meters thick on average",
      "Neptune's winds are the fastest in the solar system at 2,100 km/h",
      "There are more moons than planets — 290+ confirmed",
    ],
    timeline: [
      { year: "4.6 Byr ago", event: "Solar System Formation", detail: "Molecular cloud collapses to form the Sun and protoplanetary disk" },
      { year: "4.5 Byr ago", event: "Planet Formation", detail: "Rocky planets form through accretion in the inner system" },
      { year: "3.9 Byr ago", event: "Late Heavy Bombardment", detail: "Period of intense asteroid impacts on inner planets" },
      { year: "1610", event: "Galileo's Moons", detail: "Galileo discovers Jupiter's four largest moons" },
      { year: "1846", event: "Neptune Discovered", detail: "Neptune found through mathematical prediction" },
      { year: "2006", event: "Pluto Reclassified", detail: "IAU reclassifies Pluto as a dwarf planet" },
    ],
    missions: [
      { name: "Voyager 1", agency: "NASA", status: "Active", year: "1977", description: "Now in interstellar space, still transmitting data" },
      { name: "New Horizons", agency: "NASA", status: "Active", year: "2006", description: "Explored Pluto and Arrokoth in the Kuiper Belt" },
      { name: "Cassini-Huygens", agency: "NASA/ESA", status: "Completed", year: "1997", description: "13 years orbiting Saturn, revolutionizing our understanding" },
      { name: "Juno", agency: "NASA", status: "Active", year: "2011", description: "Currently orbiting Jupiter, studying its atmosphere and interior" },
    ],
    gallery: [
      { src: "/images/planets/saturn.png", caption: "Saturn with its majestic ring system" },
      { src: "/images/planets/jupiter.png", caption: "Jupiter's banded atmosphere" },
      { src: "/images/planets/mars.png", caption: "Mars, the Red Planet" },
      { src: "/images/planets/earth.png", caption: "Earth, our pale blue dot" },
    ],
    relatedSlugs: ["dwarf-planets", "asteroids", "comets", "nasa-missions"],
    aiPrompts: [
      "How did the Solar System form?",
      "What is the most massive planet?",
      "Could life exist elsewhere in our solar system?",
      "What lies beyond Neptune?",
    ],
    apiSource: "NASA Solar System Exploration",
  },
  "earth": {
    slug: "earth",
    title: "Earth",
    subtitle: "The Blue Marble",
    icon: "🌍",
    heroImage: "/images/planets/earth.png",
    accent: "#55aaff",
    overview: "Earth is the third planet from the Sun and the only known astronomical object to harbour life. With liquid water covering 71% of its surface, a protective magnetic field, and a nitrogen-oxygen atmosphere, Earth is uniquely suited for life. Our planet is tectonically active, with continuously moving plates that shape continents and drive volcanism.",
    stats: [
      { label: "Diameter", value: "12,742", unit: "km" },
      { label: "Mass", value: "5.972 × 10²⁴", unit: "kg" },
      { label: "Gravity", value: "9.81", unit: "m/s²" },
      { label: "Distance from Sun", value: "149.6 Million", unit: "km" },
      { label: "Day Length", value: "23h 56m" },
      { label: "Moons", value: "1" },
      { label: "Water Coverage", value: "71", unit: "%" },
      { label: "Atmosphere", value: "78% N₂, 21% O₂" },
    ],
    facts: [
      "Earth is the densest planet in the Solar System",
      "The Moon is slowly drifting away from Earth at 3.8 cm per year",
      "Earth's inner core is as hot as the surface of the Sun (~5,700°C)",
      "Only planet where plate tectonics have been confirmed",
      "The Amazon rainforest produces 20% of the world's oxygen",
      "Earth's magnetic field protects us from harmful solar radiation",
    ],
    timeline: [
      { year: "4.54 Byr ago", event: "Earth Forms", detail: "Accretion from the protoplanetary disk" },
      { year: "4.5 Byr ago", event: "Moon Formation", detail: "Giant impact creates the Moon" },
      { year: "3.8 Byr ago", event: "First Life", detail: "Earliest microbial life appears in oceans" },
      { year: "541 Myr ago", event: "Cambrian Explosion", detail: "Rapid diversification of multicellular life" },
      { year: "1957", event: "Space Age Begins", detail: "Sputnik 1 becomes first artificial satellite" },
      { year: "1972", event: "Blue Marble Photo", detail: "Apollo 17 captures iconic Earth photograph" },
    ],
    missions: [
      { name: "ISS", agency: "NASA/Roscosmos/ESA/JAXA/CSA", status: "Active", year: "1998", description: "Continuously crewed orbital laboratory since 2000" },
      { name: "Landsat 9", agency: "NASA/USGS", status: "Active", year: "2021", description: "Earth observation for land-use change detection" },
      { name: "Sentinel-6", agency: "ESA/NASA", status: "Active", year: "2020", description: "Sea level monitoring with millimetre precision" },
      { name: "DSCOVR", agency: "NOAA/NASA", status: "Active", year: "2015", description: "Full-disc Earth imagery and space weather monitoring" },
    ],
    gallery: [
      { src: "/images/planets/earth.png", caption: "Earth from space" },
    ],
    relatedSlugs: ["earth-observation", "satellites", "iss-tracker", "earth-live"],
    aiPrompts: [
      "Why is Earth the only known planet with life?",
      "How does Earth's magnetic field work?",
      "What would happen if Earth stopped rotating?",
      "How are humans changing Earth's climate?",
    ],
    apiSource: "NASA EPIC API",
  },
  "mars": {
    slug: "mars",
    title: "Mars",
    subtitle: "The Red Planet",
    icon: "🔴",
    heroImage: "/images/planets/mars.png",
    accent: "#e05020",
    overview: "Mars is the fourth planet from the Sun and the second-smallest in the Solar System. Its reddish appearance comes from iron oxide (rust) on its surface. Mars hosts the tallest volcano in the solar system — Olympus Mons at 21 km — and the longest canyon — Valles Marineris at 4,000 km. Evidence of ancient river valleys and lake beds suggests Mars once had liquid water.",
    stats: [
      { label: "Diameter", value: "6,779", unit: "km" },
      { label: "Gravity", value: "3.71", unit: "m/s²" },
      { label: "Distance from Sun", value: "227.9 Million", unit: "km" },
      { label: "Day Length", value: "24h 37m" },
      { label: "Year Length", value: "687", unit: "Earth Days" },
      { label: "Moons", value: "2 (Phobos & Deimos)" },
      { label: "Temp", value: "-63°C", unit: "Average" },
      { label: "Atmosphere", value: "95% CO₂" },
    ],
    facts: [
      "Olympus Mons is 3× the height of Mount Everest",
      "Valles Marineris is as long as the continental US",
      "Mars has the largest dust storms in the solar system",
      "A Martian day (sol) is 24 hours and 37 minutes",
      "Mars has two small moons, Phobos and Deimos",
      "Perseverance rover has produced oxygen from Martian CO₂",
    ],
    timeline: [
      { year: "1877", event: "Moons Discovered", detail: "Asaph Hall discovers Phobos and Deimos" },
      { year: "1965", event: "Mariner 4", detail: "First close-up images of Mars from NASA flyby" },
      { year: "1976", event: "Viking Landers", detail: "First successful Mars surface missions" },
      { year: "1997", event: "Mars Pathfinder", detail: "Sojourner rover operates on Mars surface" },
      { year: "2004", event: "Spirit & Opportunity", detail: "Twin rovers land, Opportunity lasts 15 years" },
      { year: "2021", event: "Perseverance Lands", detail: "Most sophisticated rover lands in Jezero Crater" },
    ],
    missions: [
      { name: "Perseverance", agency: "NASA", status: "Active", year: "2021", description: "Collecting rock samples for future return to Earth" },
      { name: "Curiosity", agency: "NASA", status: "Active", year: "2012", description: "Exploring Gale Crater for signs of ancient habitability" },
      { name: "Ingenuity", agency: "NASA", status: "Completed", year: "2021", description: "First powered flight on another planet — 72 flights total" },
      { name: "Mars Reconnaissance Orbiter", agency: "NASA", status: "Active", year: "2006", description: "High-resolution imaging from orbit" },
    ],
    gallery: [
      { src: "/images/planets/mars.png", caption: "Mars from orbit" },
    ],
    relatedSlugs: ["mars-rover", "nasa-missions", "spacecraft", "asteroids"],
    aiPrompts: [
      "Can humans live on Mars?",
      "What is Olympus Mons?",
      "What did Perseverance discover?",
      "Why is Mars red?",
    ],
    apiSource: "NASA Mars Rover Photos API",
  },
};

// Fill in remaining slugs with generated data
const REMAINING_SLUGS = [
  "dwarf-planets", "asteroids", "comets", "satellites", "spacecraft",
  "earth-observation", "space-weather", "exoplanets", "stars", "galaxies",
  "nebulae", "black-holes", "astronomy-research", "nasa-missions",
  "iss-tracker", "earth-live", "apod", "mars-rover", "neo",
];

REMAINING_SLUGS.forEach((slug) => {
  if (!SPACE_DETAIL[slug]) {
    const cat = SPACE_CATEGORIES.find((c) => c.slug === slug)!;
    SPACE_DETAIL[slug] = {
      slug,
      title: cat.title,
      subtitle: cat.subtitle,
      icon: cat.icon,
      heroImage: cat.image,
      accent: cat.accent,
      overview: cat.description,
      stats: [],
      facts: [],
      timeline: [],
      missions: [],
      gallery: [{ src: cat.image, caption: cat.title }],
      relatedSlugs: [],
      aiPrompts: [`Tell me about ${cat.title}`, `What is interesting about ${cat.title}?`],
    };
  }
});

// Inject rich data for key slugs
Object.assign(SPACE_DETAIL["spacecraft"], {
  overview: "From the first artificial satellite Sputnik 1 to the distant Voyager probes sailing in interstellar space, spacecraft have become humanity's eyes and hands across the cosmos. Modern spacecraft like the James Webb Space Telescope peer back to the first light after the Big Bang.",
  stats: [
    { label: "Voyager 1 Distance", value: "23.5 Billion", unit: "km" },
    { label: "JWST Mirror", value: "6.5", unit: "m diameter" },
    { label: "Hubble Observations", value: "1.5 Million+" },
    { label: "Active Missions", value: "60+", unit: "NASA" },
  ],
  facts: [
    "Voyager 1 is the most distant human-made object ever",
    "The ISS is as large as an American football field",
    "James Webb can see galaxies 13.6 billion light-years away",
    "The Parker Solar Probe is the fastest human-made object at 635,000 km/h",
    "Cassini collected data for 13 years around Saturn",
    "New Horizons gave us our first clear look at Pluto in 2015",
  ],
  timeline: [
    { year: "1957", event: "Sputnik 1", detail: "First artificial satellite, USSR" },
    { year: "1969", event: "Apollo 11", detail: "First crewed lunar landing" },
    { year: "1977", event: "Voyager Launch", detail: "Both Voyagers launch on grand tour" },
    { year: "1990", event: "Hubble Launch", detail: "Space Telescope transforms astronomy" },
    { year: "2021", event: "James Webb Launch", detail: "Next-generation space telescope deployed" },
    { year: "2024", event: "Europa Clipper", detail: "Mission to Jupiter's moon Europa" },
  ],
  missions: [
    { name: "James Webb Space Telescope", agency: "NASA/ESA/CSA", status: "Active", year: "2021", description: "Infrared telescope at L2, observing early universe" },
    { name: "Hubble Space Telescope", agency: "NASA/ESA", status: "Active", year: "1990", description: "34+ years of transformative astronomical observations" },
    { name: "Voyager 1", agency: "NASA", status: "Active", year: "1977", description: "In interstellar space, 23+ billion km from Earth" },
    { name: "Parker Solar Probe", agency: "NASA", status: "Active", year: "2018", description: "Closest spacecraft ever to the Sun" },
    { name: "Cassini", agency: "NASA/ESA", status: "Completed", year: "1997", description: "Studied Saturn system for 13 years" },
    { name: "New Horizons", agency: "NASA", status: "Active", year: "2006", description: "Explored Pluto and Kuiper Belt" },
  ],
  aiPrompts: [
    "How far away is Voyager 1?",
    "What can James Webb see that Hubble can't?",
    "Which spacecraft has travelled farthest?",
    "What will the Europa Clipper find?",
  ],
});

Object.assign(SPACE_DETAIL["apod"], {
  overview: "NASA's Astronomy Picture of the Day (APOD) has been publishing a new astronomical image every single day since June 16, 1995. Each image is accompanied by a brief explanation written by a professional astronomer. APOD is one of NASA's most popular websites, visited by millions worldwide.",
  stats: [
    { label: "Archive Start", value: "June 16, 1995" },
    { label: "Images Published", value: "10,000+" },
    { label: "Daily Visitors", value: "1 Million+" },
    { label: "Languages", value: "21" },
  ],
  facts: [
    "APOD has been published every day since 1995 without interruption",
    "It is one of NASA's most-accessed websites",
    "Images are selected from telescopes, spacecraft, and citizen astronomers",
    "Each image is explained by professional astronomers",
    "The archive contains over 10,000 unique images",
  ],
  aiPrompts: [
    "What is today's APOD image?",
    "How does NASA select APOD images?",
    "What has been the most popular APOD?",
    "Can I submit a photo to APOD?",
  ],
});

Object.assign(SPACE_DETAIL["black-holes"], {
  overview: "Black holes are regions of spacetime where gravity is so intense that nothing — not even electromagnetic radiation — can escape once past the event horizon. They form when massive stars collapse at the end of their lives, or through other extreme processes. In 2019, the Event Horizon Telescope produced the first image of a black hole's shadow: M87*, a supermassive black hole 6.5 billion times the mass of our Sun.",
  stats: [
    { label: "M87* Mass", value: "6.5 Billion", unit: "× Sun" },
    { label: "Sagittarius A* Mass", value: "4 Million", unit: "× Sun" },
    { label: "Event Horizon Image", value: "April 10, 2019" },
    { label: "Closest BH to Earth", value: "~1,500", unit: "light-years" },
  ],
  facts: [
    "Sagittarius A* is the supermassive black hole at the Milky Way's center",
    "Black holes don't suck — they only affect things that come too close",
    "Time passes slower near a black hole (gravitational time dilation)",
    "The first black hole ever photographed is M87* in 2019",
    "Stephen Hawking proposed that black holes slowly evaporate via Hawking radiation",
    "Supermassive black holes exist at the center of nearly all large galaxies",
  ],
  timeline: [
    { year: "1916", event: "Schwarzschild Solution", detail: "Karl Schwarzschild derives first black hole solution" },
    { year: "1967", event: "Term 'Black Hole' Coined", detail: "John Wheeler popularizes the term" },
    { year: "1974", event: "Hawking Radiation", detail: "Hawking predicts black holes slowly evaporate" },
    { year: "2015", event: "Gravitational Waves", detail: "LIGO detects waves from black hole merger" },
    { year: "2019", event: "First Image", detail: "EHT photographs M87* event horizon shadow" },
    { year: "2022", event: "Milky Way BH Imaged", detail: "EHT images Sagittarius A* for the first time" },
  ],
  aiPrompts: [
    "What happens if you fall into a black hole?",
    "How are black holes detected?",
    "What is Hawking radiation?",
    "Is there a black hole in the Milky Way?",
  ],
});

SPACE_DETAIL["launches"] = {
  slug: "launches",
  title: "Launch Tracker",
  subtitle: "Global Rocket Launches",
  icon: "🛸",
  heroImage: "/images/space-explorer/SpaceCraft.png",
  accent: "#34d399",
  overview:
    "The Launch Tracker provides real-time data on upcoming and recent rocket launches worldwide, aggregated from the Launch Library 2 open API. From SpaceX Falcon 9 missions to ISRO PSLV launches and ESA Ariane flights, every major orbital and suborbital launch is tracked here with countdown timers, mission details, and launch pad information.",
  stats: [
    { label: "Launches in 2024", value: "220+", unit: "Global" },
    { label: "Space Agencies", value: "15+", unit: "Active" },
    { label: "SpaceX Flights", value: "96+", unit: "in 2024" },
    { label: "Success Rate", value: "98.5%", unit: "(2024 avg)" },
    { label: "Orbital Missions", value: "180+", unit: "in 2024" },
    { label: "Crewed Missions", value: "8", unit: "in 2024" },
  ],
  facts: [
    "SpaceX became the first private company to launch humans to orbit in 2020",
    "Falcon 9 has the highest launch cadence of any rocket in history",
    "Starship is the largest rocket ever built at 120m tall",
    "India's PSLV has a 95%+ success rate over 60+ launches",
    "Reusable rockets have reduced launch costs by up to 90%",
  ],
  timeline: [
    { year: "1957", event: "Sputnik 1", detail: "World's first artificial satellite launched by the Soviet Union" },
    { year: "1969", event: "Apollo 11", detail: "First humans land on the Moon" },
    { year: "2015", event: "Falcon 9 Landing", detail: "SpaceX lands first orbital rocket booster" },
    { year: "2020", event: "Crew Dragon", detail: "SpaceX launches first private crewed mission to ISS" },
    { year: "2023", event: "Starship IFT-1", detail: "First integrated flight test of Starship/Super Heavy" },
  ],
  missions: [
    { name: "Starship IFT-6", agency: "SpaceX", status: "Upcoming", year: "2025", description: "Sixth integrated flight test targeting full mission profile" },
    { name: "Artemis II", agency: "NASA", status: "Upcoming", year: "2025", description: "First crewed Artemis mission — lunar flyby" },
    { name: "NISAR", agency: "NASA/ISRO", status: "Upcoming", year: "2025", description: "Joint Earth observation radar satellite" },
  ],
  gallery: [
    { src: "/images/space-explorer/SpaceCraft.png", caption: "Rocket launches: humanity's reach into space" },
  ],
  relatedSlugs: ["spacex", "nasa-missions", "iss-tracker"],
  aiPrompts: [
    "What upcoming launches should I watch?",
    "Tell me about Starship",
    "What is the most reliable rocket?",
    "How many rockets launched this year?",
  ],
  apiSource: "Launch Library 2",
};

SPACE_DETAIL["spacex"] = {
  slug: "spacex",
  title: "SpaceX",
  subtitle: "Commercial Space Leader",
  icon: "🚀",
  heroImage: "/images/space-explorer/SpaceCraft.png",
  accent: "#60a5fa",
  overview:
    "SpaceX, founded by Elon Musk in 2002, has fundamentally transformed commercial spaceflight. With reusable rockets, the Falcon 9 has become the world's most flown orbital launcher. Dragon has delivered crew and cargo to the ISS, while Starship promises fully reusable transport to the Moon, Mars, and beyond. SpaceX's cadence now exceeds all other launch providers combined.",
  stats: [
    { label: "Falcon 9 Flights", value: "350+", unit: "total" },
    { label: "Booster Reuses", value: "20+", unit: "max per booster" },
    { label: "Starlink Sats", value: "6,000+", unit: "in orbit" },
    { label: "Crewed Missions", value: "15+", unit: "to ISS" },
    { label: "Success Rate", value: "98.7%", unit: "Falcon 9" },
    { label: "Starship Height", value: "120", unit: "meters" },
  ],
  facts: [
    "Falcon 9 was the first orbital-class rocket to successfully land and refly a booster",
    "Dragon is the first commercial spacecraft certified for human spaceflight by NASA",
    "Starship produces 16.7 million pounds of thrust — more than any rocket in history",
    "SpaceX operates the world's largest private satellite constellation (Starlink)",
    "A single Falcon 9 booster has been flown 22 times",
  ],
  timeline: [
    { year: "2002", event: "SpaceX Founded", detail: "Elon Musk founds Space Exploration Technologies Corp." },
    { year: "2008", event: "Falcon 1 Orbit", detail: "First privately developed liquid-fueled rocket to reach orbit" },
    { year: "2012", event: "Dragon CRS-1", detail: "First private spacecraft to berth with the ISS" },
    { year: "2015", event: "Booster Landing", detail: "Falcon 9 first stage lands at Cape Canaveral" },
    { year: "2020", event: "Crew Dragon Demo-2", detail: "First private crewed spaceflight to the ISS" },
    { year: "2023", event: "Starship Test Flights", detail: "IFT-1 through IFT-4 progressively successful" },
  ],
  missions: [
    { name: "Crew Dragon Endurance", agency: "SpaceX/NASA", status: "Active", year: "2024", description: "Commercial Crew rotation mission to ISS" },
    { name: "Starlink v2 Mini", agency: "SpaceX", status: "Active", year: "2024", description: "Next-gen Starlink satellites with 4× capacity" },
    { name: "Polaris Dawn", agency: "SpaceX", status: "Completed", year: "2024", description: "First private spacewalk in history" },
  ],
  gallery: [
    { src: "/images/space-explorer/SpaceCraft.png", caption: "SpaceX Dragon capsule on approach to ISS" },
  ],
  relatedSlugs: ["launches", "nasa-missions", "spacecraft"],
  aiPrompts: [
    "Tell me about Starship",
    "How does Falcon 9 land?",
    "What is Dragon spacecraft?",
    "How many Starlink satellites are in orbit?",
    "Compare SpaceX to NASA",
  ],
};

SPACE_DETAIL["exoplanets"] = {
  slug: "exoplanets",
  title: "Exoplanets",
  subtitle: "Worlds Beyond Our Sun",
  icon: "🪐",
  heroImage: "/images/space-explorer/ExoPlanet.png",
  accent: "#a78bfa",
  overview:
    "An exoplanet is any planet that orbits a star other than our Sun. As of 2024, NASA's Exoplanet Archive contains over 5,700 confirmed discoveries. The James Webb Space Telescope is now characterizing their atmospheres, searching for biosignatures — chemical signs of life. From ultra-hot Jupiters to potentially habitable super-Earths, the diversity of worlds is staggering.",
  stats: [
    { label: "Confirmed Exoplanets", value: "5,700+", unit: "as of 2024" },
    { label: "Habitable Zone Candidates", value: "60+", unit: "Earth-like" },
    { label: "Detection Methods", value: "7+", unit: "techniques" },
    { label: "TRAPPIST-1 Planets", value: "7", unit: "(3 in HZ)" },
    { label: "Nearest Exoplanet", value: "4.2", unit: "light years" },
    { label: "JWST Atmospheres", value: "25+", unit: "characterized" },
  ],
  facts: [
    "Proxima Centauri b is the closest known exoplanet at just 4.2 light years away",
    "TRAPPIST-1 system has 3 planets in the habitable zone around a single star",
    "K2-18b may have a water-rich atmosphere detectable by JWST",
    "Some exoplanets orbit their stars in less than 1 Earth day",
    "The first confirmed exoplanet discovery was in 1992, orbiting a pulsar",
    "NASA's Kepler mission discovered over 2,600 exoplanets alone",
  ],
  timeline: [
    { year: "1992", event: "First Exoplanet", detail: "Wolszczan & Frail discover planets orbiting pulsar PSR 1257+12" },
    { year: "1995", event: "51 Pegasi b", detail: "First exoplanet found around a Sun-like star" },
    { year: "2009", event: "Kepler Launched", detail: "NASA's planet-hunting telescope begins operations" },
    { year: "2017", event: "TRAPPIST-1", detail: "Seven Earth-sized planets discovered around nearby dwarf star" },
    { year: "2021", event: "JWST Launch", detail: "James Webb Space Telescope begins atmospheric characterization" },
    { year: "2023", event: "K2-18b Atmosphere", detail: "JWST detects possible dimethyl sulfide — potential biosignature" },
  ],
  missions: [
    { name: "James Webb Space Telescope", agency: "NASA/ESA/CSA", status: "Active", year: "2021", description: "Characterizing exoplanet atmospheres in unprecedented detail" },
    { name: "TESS", agency: "NASA", status: "Active", year: "2018", description: "Transiting Exoplanet Survey Satellite — all-sky planet finder" },
    { name: "CHEOPS", agency: "ESA", status: "Active", year: "2019", description: "Characterising Exoplanet Satellite — precise radius measurements" },
    { name: "PLATO", agency: "ESA", status: "Upcoming", year: "2026", description: "PLAnetary Transits and Oscillations — Earth-twin search" },
  ],
  gallery: [
    { src: "/images/space-explorer/ExoPlanet.png", caption: "Artist's conception of a habitable exoplanet" },
  ],
  relatedSlugs: ["astronomy-research", "stars", "nasa-missions"],
  aiPrompts: [
    "Which exoplanet is most like Earth?",
    "How do we detect exoplanets?",
    "Tell me about TRAPPIST-1",
    "Could life exist on K2-18b?",
    "What is the habitable zone?",
  ],
  apiSource: "NASA Exoplanet Archive",
};

export function getCategoryBySlug(slug: string): SpaceCategory | undefined {
  return SPACE_CATEGORIES.find((c) => c.slug === slug);
}

export function getDetailBySlug(slug: string): SpaceDetailData | undefined {
  return SPACE_DETAIL[slug];
}
